'use strict';

// Une lacune concrète par module : deux exemples différents, le fichier exact,
// sa commande, le résultat observable et un cas à corriger. Aucun de ces blocs
// n'est présenté comme relu par un expert externe.
const exemples = [
  {
    id: 'html-formulaire-transmission', domaine: 'html', titre: 'Comprendre ce qu’un formulaire envoie vraiment', niveau: 1,
    situation: 'Un champ visible fonctionne à l’écran, mais le serveur ne reçoit pas sa valeur. Le nom affiché du champ et son attribut name n’ont pas le même rôle.',
    notion: 'Un form regroupe des contrôles. action désigne la destination et method la méthode HTTP. Le label nomme le champ pour la personne ; name nomme la donnée envoyée. Un bouton submit lance l’envoi. La validation du navigateur facilite la saisie, mais le serveur doit vérifier à nouveau.',
    fichier: 'formulaire.html', langage: 'HTML',
    code: '<!doctype html>\n<html lang="fr"><head><meta charset="utf-8"><title>Inscription</title></head>\n<body><main><h1>Inscription</h1>\n<form action="/inscriptions" method="post">\n  <label for="nom">Votre nom</label>\n  <input id="nom" name="nom" required maxlength="80">\n  <button type="submit">Envoyer</button>\n</form></main></body></html>',
    second: '<!-- Variation : name change la clé envoyée, pas le texte visible -->\n<input id="nom" name="personne" required maxlength="80">',
    detail: 'id relie le label au champ. name="nom" produit une clé nom dans les données du formulaire. required bloque une valeur vide dans le navigateur. maxlength limite la saisie visible à 80 caractères, mais ne remplace pas une limite au serveur.',
    lancer: 'Ouvrez formulaire.html dans le navigateur. Pour voir un envoi réussi, servez la page depuis une application qui répond à POST /inscriptions ; sans ce serveur, l’échec réseau est attendu et ne prouve pas que le HTML est invalide.',
    attendu: 'Tab atteint le champ et le bouton. En saisissant Ada puis en envoyant, le navigateur prépare nom=Ada pour POST /inscriptions. Dans la variante, la clé préparée devient personne.',
    erreur: 'Supprimer name laisse le champ visible mais retire sa valeur des données envoyées. Vérifiez la charge utile dans l’onglet Réseau des outils du navigateur.',
    exercice: 'Ajoutez un champ email avec label, id, name, type="email" et required. Prédisez les deux clés envoyées.',
    correction: 'Le formulaire contient un deuxième label relié à <input id="email" name="email" type="email" required>. Les clés envoyées sont nom et email ; le texte des labels ne devient pas automatiquement une clé.',
    source: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Your_first_form'
  },
  {
    id: 'css-cascade-debug', domaine: 'css', titre: 'Déboguer la cascade sans empiler des règles', niveau: 2,
    situation: 'Une carte reste bleue alors que vous venez d’ajouter une règle verte. Il faut identifier la règle gagnante avant de modifier encore le CSS.',
    notion: 'La cascade compare origine, importance, couche, spécificité, portée et ordre. Pour un premier diagnostic, inspectez la déclaration appliquée et celles barrées dans les outils du navigateur. Les classes de composant rendent souvent les règles plus lisibles que les sélecteurs de plus en plus longs.',
    fichier: 'styles.css', langage: 'CSS',
    code: '.carte { color: #1d4ed8; }\n.carte--alerte { color: #b91c1c; }\n/* <article class="carte carte--alerte"> : rouge */',
    second: '.carte { padding: 1rem; width: min(100%, 32rem); }\n*, *::before, *::after { box-sizing: border-box; }\n@media (max-width: 30rem) { .carte { padding: .75rem; } }',
    detail: 'La règle .carte--alerte vient après .carte et possède la même spécificité : elle gagne pour color. box-sizing inclut bordure et padding dans la largeur calculée ; la media query change la marge intérieure sur un écran étroit.',
    lancer: 'Créez une page HTML avec <article class="carte carte--alerte">Alerte</article> et liez styles.css. Inspectez color, padding et width. Réduisez la fenêtre sous 30rem.',
    attendu: 'Le texte est rouge ; la carte ne dépasse pas 32rem ni son conteneur. Sur écran étroit, le padding devient .75rem.',
    erreur: 'Ajouter !important partout masque le conflit sans l’expliquer. Dans DevTools, lisez la règle gagnante et la raison avant de changer le sélecteur.',
    exercice: 'Ajoutez .carte--succes après .carte--alerte ; faites-la verte et expliquez le résultat si l’élément porte les trois classes.',
    correction: 'Si .carte--succes vient après et a la même spécificité, sa couleur gagne. Mieux vaut éviter d’appliquer simultanément deux états contradictoires à la même carte.',
    source: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade/Cascade'
  },
  {
    id: 'js-retour-portee', domaine: 'javascript', titre: 'Suivre paramètres, portée et valeur de retour', niveau: 1,
    situation: 'Une fonction affiche un résultat correct, mais le code qui l’appelle reçoit undefined. Afficher une valeur et la renvoyer sont deux opérations distinctes.',
    notion: 'Un paramètre est un nom local à la fonction. return donne une valeur à l’appelant et arrête cette exécution. Une variable déclarée avec const dans la fonction ne devient pas globale. Traitez séparément calcul, retour et affichage.',
    fichier: 'main.js', langage: 'JavaScript',
    code: 'function prixTtc(prixHt, taux) {\n  const montantTaxe = prixHt * taux;\n  return Math.round((prixHt + montantTaxe) * 100) / 100;\n}\nconst total = prixTtc(10, 0.2);\nconsole.log(total); // 12',
    second: 'function prixTtcIncorrect(prixHt, taux) {\n  console.log(prixHt * (1 + taux));\n}\nconsole.log(prixTtcIncorrect(10, 0.2)); // affiche 12 puis undefined',
    detail: 'prixHt et taux reçoivent 10 et 0.2 ; montantTaxe vaut 2. return transmet 12 à total. Dans la seconde fonction, console.log produit une sortie mais aucune instruction return ne transmet de valeur.',
    lancer: 'Enregistrez main.js puis exécutez node main.js ; vous pouvez aussi coller chaque bloc dans la console du navigateur.',
    attendu: 'Le premier bloc affiche 12. Le second affiche 12 puis undefined. Le résultat calculé ne dépend pas d’une variable globale cachée.',
    erreur: 'Utiliser une variable interne hors de la fonction produit ReferenceError ; utilisez la valeur retournée, pas un nom local inaccessible.',
    exercice: 'Écrivez prixTtc(20, 0.1) et annoncez la valeur avant exécution. Remplacez ensuite return par console.log et expliquez le nouvel affichage.',
    correction: 'prixTtc(20, 0.1) renvoie 22. Sans return, l’appel renvoie undefined même si un console.log dans la fonction affiche 22.',
    source: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions'
  },
  {
    id: 'dom-evenement-cible', domaine: 'dom', titre: 'Distinguer cible du clic et élément qui écoute', niveau: 2,
    situation: 'Un clic sur le texte d’un bouton fonctionne, mais un clic sur son icône ne répond pas. Le clic vient d’un enfant du bouton.',
    notion: 'event.target désigne le nœud initialement visé ; event.currentTarget désigne l’élément dont le gestionnaire s’exécute. Avec la délégation, cherchez le bouton le plus proche de la cible puis vérifiez qu’il appartient bien à la liste.',
    fichier: 'app.js', langage: 'JavaScript',
    code: 'const liste = document.querySelector("#actions");\nliste.addEventListener("click", (event) => {\n  const bouton = event.target.closest("button[data-action]");\n  if (!bouton || !liste.contains(bouton)) return;\n  document.querySelector("#etat").textContent = bouton.dataset.action;\n});',
    second: '<ul id="actions"><li><button type="button" data-action="ouvrir"><span>Ouvrir</span></button></li></ul>\n<p id="etat" role="status"></p>\n<script src="app.js" defer></script>',
    detail: 'Le gestionnaire est posé une fois sur #actions. closest remonte du span éventuel au bouton. contains évite qu’un bouton extérieur soit traité. textContent affiche la valeur comme texte, sans interpréter du HTML.',
    lancer: 'Placez le deuxième bloc dans le body d’un index.html et le premier dans app.js. Ouvrez index.html et cliquez directement sur le mot Ouvrir.',
    attendu: 'Le paragraphe d’état affiche ouvrir, que le clic touche le texte ou le bord du bouton.',
    erreur: 'Comparer event.target.tagName à BUTTON échoue lorsque la cible réelle est span. Inspectez target et currentTarget pour voir la différence.',
    exercice: 'Ajoutez un second bouton data-action="fermer" et prédisez le nouveau texte après son clic.',
    correction: 'Le même gestionnaire fonctionne sans ajout de listener. Le paragraphe affiche fermer ; aucun HTML utilisateur n’est injecté.',
    source: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Event_bubbling'
  },
  {
    id: 'node-chemins-processus', domaine: 'node', titre: 'Ne plus confondre dossier courant et dossier du script', niveau: 2,
    situation: 'Un script lit note.txt depuis le dossier du projet, mais échoue quand un collègue le lance depuis un autre dossier.',
    notion: 'process.cwd() est le dossier d’où la commande est lancée. __dirname, dans un module CommonJS, est le dossier du fichier source. Choisissez la base du chemin selon le contrat : donnée fournie par l’utilisateur ou ressource livrée avec le programme.',
    fichier: 'lire.js', langage: 'JavaScript',
    code: 'const fs = require("node:fs");\nconst path = require("node:path");\nconst fichier = path.join(__dirname, "note.txt");\nconsole.log(fs.readFileSync(fichier, "utf8").trim());',
    second: 'const path = require("node:path");\nconst nom = process.argv[2] || "note.txt";\nconst fichierUtilisateur = path.resolve(process.cwd(), nom);\nconsole.log(fichierUtilisateur);',
    detail: 'Le premier script lit une ressource voisine de lire.js ; le second construit un chemin à partir du dossier courant et d’un argument. path.join et path.resolve assemblent les chemins selon le système sans concaténer manuellement des séparateurs.',
    lancer: 'Créez lire.js et note.txt contenant Bonjour dans le même dossier. Exécutez node lire.js depuis ce dossier, puis depuis son parent avec node sous-dossier/lire.js.',
    attendu: 'Le premier script lit Bonjour dans les deux cas. Le second affiche un chemin différent si le dossier courant change.',
    erreur: 'Utiliser readFileSync("note.txt") suppose implicitement que process.cwd() contient la note. La trace ENOENT aide à voir quel chemin a été tenté.',
    exercice: 'Prédisez le chemin produit par path.resolve(process.cwd(), "notes/a.txt") après un changement de dossier.',
    correction: 'Le chemin dépend du nouveau process.cwd(), pas de l’emplacement du fichier JavaScript. Affichez process.cwd() pour le vérifier.',
    source: 'https://nodejs.org/api/process.html#processcwd'
  },
  {
    id: 'npm-script-verification', domaine: 'npm', titre: 'Relier package.json, commande et code exécuté', niveau: 2,
    situation: 'La commande npm run check échoue sur un autre poste : le manifeste annonce un fichier qui n’existe pas ou une dépendance absente.',
    notion: 'Le bloc scripts de package.json associe un nom court à une commande. npm install résout les dépendances et écrit un lockfile ; npm ci réinstalle depuis ce lockfile en environnement reproductible. Un script n’installe ni ne crée tout seul le fichier qu’il appelle.',
    fichier: 'package.json', langage: 'JSON',
    code: '{\n  "name": "atelier-verification",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": { "start": "node index.js", "check": "node --check index.js" }\n}',
    second: '// index.js — un fichier réel à côté de package.json\nconst message = "Prêt";\nconsole.log(message);',
    detail: 'start lance index.js ; check demande à Node de contrôler sa syntaxe. private évite une publication accidentelle. Le lockfile décrit les versions résolues des dépendances quand il y en a.',
    lancer: 'Créez les deux fichiers dans un même dossier. Exécutez npm run check puis npm start. Pour ce projet sans dépendance, aucun téléchargement n’est nécessaire.',
    attendu: 'check se termine sans erreur et start affiche Prêt. Si vous renommez index.js, les deux commandes échouent tant que package.json n’est pas mis à jour.',
    erreur: 'Lancer npm ci sans package-lock.json produit une erreur : créez et conservez le lockfile lors de l’ajout de vraies dépendances.',
    exercice: 'Ajoutez un script "test" qui lance node --test ; créez un premier fichier de test avant de déclarer la vérification terminée.',
    correction: '"test": "node --test" dans scripts, puis un fichier de test réel. Un script qui sort avec 0 sans vérifier le comportement n’apporte pas de preuve.',
    source: 'https://docs.npmjs.com/cli/using-npm/scripts'
  },
  {
    id: 'http-contrat-reponse', domaine: 'http', titre: 'Lire statut, en-têtes et corps comme un contrat', niveau: 2,
    situation: 'Le client reçoit un JSON d’erreur avec le statut 200 et le traite comme une réussite. Le corps seul ne suffit pas à comprendre la réponse.',
    notion: 'Une réponse HTTP a une ligne de statut, des en-têtes et un corps éventuel. Le statut indique la catégorie de résultat ; Content-Type annonce comment interpréter le corps. Une API cohérente distingue succès, entrée invalide, ressource absente et panne serveur.',
    fichier: 'transcriptions HTTP à lire', langage: 'HTTP',
    code: 'GET /api/livres/42 HTTP/1.1\nHost: localhost:3000\nAccept: application/json\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{"id":42,"titre":"Web"}',
    second: 'GET /api/livres/inconnu HTTP/1.1\nHost: localhost:3000\nAccept: application/json\n\nHTTP/1.1 404 Not Found\nContent-Type: application/json\n\n{"erreur":"livre introuvable"}',
    detail: 'GET demande une lecture. Host indique le serveur visé. Accept annonce le format souhaité ; Content-Type décrit le format réellement envoyé. Le corps JSON n’est pas un statut : une erreur avec 200 tromperait le client.',
    lancer: 'Lisez ces deux échanges comme des exemples de protocole, pas comme un seul fichier à exécuter. Avec une API locale équivalente, utilisez curl -i http://localhost:3000/api/livres/42 pour voir réellement la ligne de statut et les en-têtes.',
    attendu: 'La première réponse représente un livre trouvé ; la seconde une ressource absente. L’API peut expliquer une erreur sans annoncer un succès.',
    erreur: 'fetch ne rejette pas sur 404 : le client doit consulter response.ok ou response.status avant de traiter le JSON comme un livre.',
    exercice: 'Quel statut et quel corps proposeriez-vous pour un identifiant mal formé, distinct d’un livre inexistant ?',
    correction: '400 Bad Request avec une erreur de validation décrit une entrée mal formée ; 404 Not Found décrit une entrée valide dont la ressource n’existe pas.',
    source: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview'
  },
  {
    id: 'express-frontiere-entree', domaine: 'express', titre: 'Valider un corps JSON avant toute écriture', niveau: 3,
    situation: 'Une route accepte un objet sans titre, puis l’application enregistre undefined. Le premier contrôle doit être au bord de la route.',
    notion: 'express.json() lit un corps JSON, mais ne prouve pas que ses champs sont valides. La route doit définir taille, type, valeur et réponse d’échec. Retourner après res.status(...).json(...) évite d’envoyer une deuxième réponse.',
    fichier: 'server.js', langage: 'JavaScript',
    code: 'const express = require("express");\nconst app = express();\napp.use(express.json({ limit: "16kb" }));\nconst notes = [];\napp.post("/api/notes", (req, res) => {\n  const titre = req.body?.titre;\n  if (typeof titre !== "string" || !titre.trim() || titre.length > 80)\n    return res.status(400).json({ erreur: "titre invalide" });\n  const note = { id: notes.length + 1, titre: titre.trim() };\n  notes.push(note);\n  return res.status(201).json(note);\n});\napp.listen(3000);',
    second: 'curl -i -X POST http://localhost:3000/api/notes \\\n  -H "Content-Type: application/json" \\\n  -d \'{"titre":"Lire"}\'\n# Test d’échec : remplacez le corps par {}.',
    detail: 'La limite protège contre un corps excessif ; elle ne remplace pas la validation métier. ?. empêche une lecture sur undefined. 400 explique une saisie invalide ; 201 annonce la création. Le tableau en mémoire disparaît au redémarrage.',
    lancer: 'Dans un dossier de test, exécutez npm init -y, npm install express, créez server.js puis node server.js. Dans un second terminal, lancez les deux requêtes curl.',
    attendu: 'Le premier POST renvoie 201 et un id. Le second renvoie 400 ; aucune note vide n’est enregistrée.',
    erreur: 'Construire une requête SQL par concaténation après ce contrôle reste dangereux : utilisez des paramètres de requête dans une vraie base.',
    exercice: 'Ajoutez GET /api/notes qui renvoie {donnees: notes}. Expliquez pourquoi ce tableau ne convient pas à une persistance de production.',
    correction: 'app.get("/api/notes", (_req, res) => res.json({ donnees: notes })); montre l’état en mémoire. Au redémarrage le tableau est vide ; une base avec contraintes et sauvegarde sera nécessaire.',
    source: 'https://expressjs.com/en/guide/using-middleware.html'
  },
  {
    id: 'shell-chemins-cites', domaine: 'shell', titre: 'Travailler avec des chemins contenant des espaces', niveau: 2,
    situation: 'Un script marche dans projet-web mais échoue dans Mon projet. Le shell coupe un chemin non cité en plusieurs arguments.',
    notion: 'Une variable peut contenir un chemin entier. En Bash/Zsh, citez "$variable" quand elle sert d’argument. Affichez pwd et listez les fichiers avant une opération qui écrit ou déplace. PowerShell utilise des commandes différentes pour certaines opérations.',
    fichier: 'exercice.sh', langage: 'Bash',
    code: '#!/usr/bin/env bash\nset -euo pipefail\ndossier="Mon projet"\nmkdir -p "$dossier"\nprintf "Bonjour\\n" > "$dossier/note.txt"\nprintf "Dossier : %s\\n" "$PWD"\ncat "$dossier/note.txt"',
    second: 'Get-Location\nNew-Item -ItemType Directory -Force -Path "Mon projet"\nSet-Content -Path "Mon projet/note.txt" -Value "Bonjour"\nGet-Content -Path "Mon projet/note.txt"',
    detail: 'Les guillemets conservent Mon projet comme un seul chemin. set -euo pipefail signale plus tôt les échecs dans ce script d’essai. Le bloc PowerShell exprime la même intention avec ses propres commandes.',
    lancer: 'Dans un dossier sans fichiers importants, lancez bash exercice.sh sur Linux/macOS, ou les lignes PowerShell une par une sur Windows. Vérifiez ensuite le fichier avec votre gestionnaire de fichiers.',
    attendu: 'Un sous-dossier Mon projet contient note.txt et le terminal affiche Bonjour. Aucun autre dossier n’est modifié.',
    erreur: 'mkdir -p $dossier sans guillemets peut créer deux dossiers Mon et projet. Affichez les chemins avant de nettoyer ; ne lancez pas de suppression globale.',
    exercice: 'Changez le nom du dossier en « Mes notes » et prédisez les noms créés avec puis sans guillemets.',
    correction: 'Avec "$dossier", un seul dossier Mes notes apparaît. Sans guillemets dans un contexte de découpage Bash, Mes et notes peuvent devenir des arguments séparés.',
    source: 'https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html'
  },
  {
    id: 'typescript-frontiere-unknown', domaine: 'typescript', titre: 'Valider unknown avant de croire une API', niveau: 4,
    situation: 'Une réponse annonce un livre dans le code, mais renvoie réellement une page d’erreur. Le type TypeScript disparaît à l’exécution.',
    notion: 'unknown oblige à vérifier avant de lire les propriétés. Un garde de type vérifie les champs utilisés ; une assertion as Livre ne valide rien. Le code qui consomme la donnée peut ensuite compter sur un contrat explicite.',
    fichier: 'index.ts', langage: 'TypeScript',
    code: 'type Livre = { id: number; titre: string };\nfunction estLivre(valeur: unknown): valeur is Livre {\n  if (typeof valeur !== "object" || valeur === null) return false;\n  const objet = valeur as Record<string, unknown>;\n  return typeof objet.id === "number" && Number.isInteger(objet.id) && typeof objet.titre === "string";\n}\nconst donnees: unknown = JSON.parse("{\\"id\\":1,\\"titre\\":\\"Web\\"}");\nif (!estLivre(donnees)) throw new Error("Réponse invalide");\nconsole.log(donnees.titre);',
    second: 'const absente: unknown = JSON.parse("{\\"id\\":1}");\nconsole.log(estLivre(absente)); // false : titre manque',
    detail: 'Le test null est nécessaire car typeof null vaut object. Record<string, unknown> autorise la lecture des clés sans leur donner un type de confiance. Number.isInteger et typeof contrôlent les deux champs avant l’accès à titre.',
    lancer: 'Dans un dossier TypeScript configuré avec strict, copiez les deux blocs dans index.ts puis exécutez npx tsc --noEmit. Exécutez le JavaScript compilé selon la configuration du projet.',
    attendu: 'Le premier bloc affiche Web ; le second affiche false. Le compilateur ne remplace pas cette vérification des données reçues.',
    erreur: 'Écrire JSON.parse(...) as Livre fait taire TypeScript mais n’ajoute aucun contrôle pendant l’exécution.',
    exercice: 'Ajoutez une limite de longueur pour titre et testez un objet dont titre est une chaîne vide.',
    correction: 'Après typeof objet.titre === "string", vérifiez objet.titre.trim().length > 0 et une borne maximale ; le garde doit refuser la chaîne vide.',
    source: 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html'
  },
  {
    id: 'react-etat-derive', domaine: 'react', titre: 'Calculer une liste filtrée sans état en double', niveau: 4,
    situation: 'Après l’ajout d’un livre, la liste affichée reste ancienne : le composant garde à la fois la source et une copie filtrée dans deux états.',
    notion: 'Un état sert aux valeurs que l’utilisateur modifie. Une liste filtrée calculable depuis livres et recherche est une valeur dérivée ; la recalculer pendant le rendu évite une synchronisation fragile. Chaque élément rendu doit garder une clé stable.',
    fichier: 'src/App.jsx', langage: 'JSX',
    code: 'import { useState } from "react";\nconst initial = [{ id: 1, titre: "Web" }, { id: 2, titre: "Code" }];\nexport default function App() {\n  const [livres, setLivres] = useState(initial);\n  const [recherche, setRecherche] = useState("");\n  const visibles = livres.filter(livre => livre.titre.toLowerCase().includes(recherche.toLowerCase()));\n  return <main><h1>Livres</h1><label>Rechercher <input value={recherche} onChange={e => setRecherche(e.target.value)} /></label>\n    <button type="button" onClick={() => setLivres(l => [...l, { id: 3, titre: "Réseau" }])}>Ajouter</button>\n    <ul>{visibles.map(livre => <li key={livre.id}>{livre.titre}</li>)}</ul></main>;\n}',
    second: '// À éviter : un deuxième useState pour visibles suivi d’un effet qui copie livres.\n// Deux sources de vérité doivent alors rester synchronisées à chaque changement.',
    detail: 'setLivres reçoit la valeur précédente et produit un nouveau tableau. filter ne modifie pas livres. key utilise id, stable même si l’ordre change ; l’index serait fragile. Le label donne un nom au champ.',
    lancer: 'Créez un projet React avec un outil compatible, par exemple Vite ; remplacez src/App.jsx puis lancez npm run dev. Essayez la recherche avant et après Ajouter.',
    attendu: 'La liste suit la saisie immédiatement. Effacez la recherche pour revoir tous les livres ; aucun effet de synchronisation n’est nécessaire.',
    erreur: 'Cliquer plusieurs fois sur Ajouter réutilise id 3 : une vraie application doit générer un identifiant unique. Inspectez les avertissements React liés aux clés.',
    exercice: 'Modifiez l’ajout pour créer un id unique dans cette petite démo, puis vérifiez qu’un filtre actif reste correct.',
    correction: 'Un compteur local ou crypto.randomUUID() convient à une démonstration côté client ; dans une application partagée, l’identifiant durable vient du système de données.',
    source: 'https://react.dev/learn/you-might-not-need-an-effect'
  },
  {
    id: 'next-frontiere-composants', domaine: 'nextjs', titre: 'Choisir entre composant serveur et interaction cliente', niveau: 4,
    situation: 'Une page Next.js tente d’utiliser useState côté serveur. Il faut isoler la partie interactive au lieu de déplacer toute la page vers le navigateur.',
    notion: 'Dans App Router, un composant serveur peut préparer une page et lire des données sur le serveur. Un composant marqué "use client" peut gérer des interactions et des hooks côté navigateur. Les props qui traversent cette frontière doivent être sérialisables.',
    fichier: 'app/page.tsx', langage: 'TSX',
    code: '// app/page.tsx — composant serveur\nimport Compteur from "./compteur";\nexport default function Page() {\n  return <main><h1>Bibliothèque</h1><p>Page rendue par le serveur.</p><Compteur /></main>;\n}',
    second: '// app/compteur.tsx — seul ce composant est interactif\n"use client";\nimport { useState } from "react";\nexport default function Compteur() {\n  const [n, setN] = useState(0);\n  return <button type="button" onClick={() => setN(n + 1)}>Lectures : {n}</button>;\n}',
    detail: 'page.tsx ne porte pas la directive cliente. compteur.tsx la porte au début du fichier et peut utiliser useState. Le bouton est une action ; le titre et le paragraphe n’ont pas besoin du code interactif.',
    lancer: 'Créez un projet avec create-next-app en choisissant App Router et sans dossier src, puis placez les deux fichiers dans app/. Lancez npm run dev et ouvrez /. Si vous avez choisi src, utilisez src/app/.',
    attendu: 'La page s’ouvre et le nombre augmente au clic. Le HTML non interactif n’a pas besoin d’être converti en composant client.',
    erreur: 'Ajouter "use client" au hasard masque la frontière. Si une prop est une fonction créée sur le serveur, elle ne traverse pas simplement cette frontière.',
    exercice: 'Ajoutez un titre de livre passé comme chaîne depuis Page vers Compteur et expliquez pourquoi cette donnée traverse la frontière.',
    correction: 'Une chaîne est sérialisable : <Compteur titre="Web" /> puis une prop titre dans Compteur fonctionne. Une fonction ordinaire côté serveur ne devient pas automatiquement un callback client.',
    source: 'https://nextjs.org/docs/app/getting-started/server-and-client-components'
  },
  {
    id: 'vue-valeur-derivee', domaine: 'vue', titre: 'Distinguer ref, computed et action utilisateur', niveau: 4,
    situation: 'Une liste filtrée n’est mise à jour qu’au premier chargement. Elle a été copiée dans un état au lieu d’être calculée à partir du terme et des livres.',
    notion: 'ref contient une valeur réactive modifiable ; computed décrit une valeur dérivée des refs lues. Dans un composant <script setup>, le template déplie les refs. Une liste rendue doit garder une clé stable.',
    fichier: 'src/App.vue', langage: 'Vue',
    code: '<script setup>\nimport { computed, ref } from "vue";\nconst terme = ref("");\nconst livres = ref([{ id: 1, titre: "Web" }, { id: 2, titre: "Code" }]);\nconst visibles = computed(() => livres.value.filter(livre => livre.titre.toLowerCase().includes(terme.value.toLowerCase())));\n</script>\n<template>\n  <main><h1>Livres</h1><label>Rechercher <input v-model="terme"></label>\n    <ul><li v-for="livre in visibles" :key="livre.id">{{ livre.titre }}</li></ul></main>\n</template>',
    second: '<!-- Variante dans le template : un état vide explicite -->\n<p v-if="visibles.length === 0" role="status">Aucun livre trouvé</p>',
    detail: 'terme.value est lu par computed ; ce calcul est mis à jour quand terme change. v-model relie le champ et ref. :key identifie chaque livre. Le message vide explique un résultat absent sans inventer des données.',
    lancer: 'Créez un projet avec npm create vue@latest, remplacez src/App.vue, puis npm install et npm run dev.',
    attendu: 'Saisir Web ne laisse qu’un résultat. Un terme inconnu donne une liste vide ; la variante annonce explicitement cet état.',
    erreur: 'Modifier directement une prop reçue d’un parent crée une source de vérité confuse. Émettez une action vers le parent ou gardez l’état local selon le besoin.',
    exercice: 'Ajoutez un bouton qui insère un livre avec un id inédit et observez que computed se met à jour.',
    correction: 'livres.value.push({ id: 3, titre: "Réseau" }) modifie la source locale ; la valeur dérivée est recalculée. Dans un projet durable, les identifiants viennent du modèle de données.',
    source: 'https://vuejs.org/guide/essentials/computed.html'
  },
  {
    id: 'angular-imports-autonomes', domaine: 'angular', titre: 'Comprendre les imports d’un composant autonome', niveau: 4,
    situation: 'Un template utilise un composant enfant mais Angular annonce qu’il est inconnu. L’import TypeScript seul ne suffit pas à rendre le composant disponible dans le template.',
    notion: 'Un composant standalone déclare les dépendances de son template dans imports. Une classe importée par TypeScript n’est pas automatiquement visible dans le template. Le composant enfant expose des données avec input et des actions avec output.',
    fichier: 'src/app/app.ts', langage: 'TypeScript',
    code: 'import { Component } from "@angular/core";\n@Component({ selector: "app-carte", standalone: true, template: `<article><h2>Web</h2></article>` })\nexport class Carte {}\n@Component({ selector: "app-root", standalone: true, imports: [Carte], template: `<main><h1>Livres</h1><app-carte /></main>` })\nexport class App {}',
    second: '// Sans imports: [Carte], <app-carte> n’est pas une dépendance connue\n// du template du composant App, même si import { Carte } existe.',
    detail: 'selector donne le nom HTML du composant enfant. standalone signifie qu’il n’a pas besoin d’un NgModule de déclaration. imports: [Carte] relie explicitement le template de App à Carte.',
    lancer: 'Créez un projet Angular avec la CLI et remplacez le contenu de src/app/app.ts dans un projet qui démarre App comme composant racine. Lancez npm start.',
    attendu: 'La page montre Livres puis Web. Supprimer Carte de imports provoque une erreur de template ; le remettre rétablit le rendu.',
    erreur: 'Ajouter CUSTOM_ELEMENTS_SCHEMA pour faire taire toute erreur peut cacher une faute de nom. Vérifiez d’abord selector et imports.',
    exercice: 'Ajoutez une deuxième carte avec un titre différent. Expliquez pourquoi une prop input serait préférable à deux classes presque identiques.',
    correction: 'Un input permet de passer le titre au composant réutilisable ; dupliquer la classe rend les corrections futures incohérentes. Le parent reste responsable des deux données.',
    source: 'https://angular.dev/guide/components/importing'
  },
  {
    id: 'css-outils-couche-style', domaine: 'css-outils', titre: 'Faire fonctionner une classe utilitaire réellement chargée', niveau: 4,
    situation: 'Une classe grid-cols-2 est présente dans le HTML, mais la page reste en une colonne. Le navigateur ne connaît pas une classe tant que le CSS correspondant n’a pas été chargé ou compilé.',
    notion: 'Une classe est seulement un nom dans HTML. Tailwind produit des règles CSS pour les classes détectées dans le projet ; Bootstrap livre des règles prêtes à charger. Vérifiez l’onglet Styles et le CSS final avant de changer au hasard les classes.',
    fichier: 'index.html', langage: 'HTML',
    code: '<!doctype html>\n<html lang="fr"><head><meta charset="utf-8"><title>Grille</title><link rel="stylesheet" href="styles.css"></head>\n<body><main><h1>Deux cartes</h1><div class="grille"><article>Une</article><article>Deux</article></div></main></body></html>',
    second: '/* styles.css — résultat équivalent sans dépendance */\n.grille { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1rem; }\n@media (max-width: 36rem) { .grille { grid-template-columns: 1fr; } }',
    detail: 'Le lien stylesheet rend les règles disponibles. display:grid active la grille, grid-template-columns crée deux colonnes et la media query revient à une colonne sur un écran étroit. Remplacer les classes par des utilitaires exige de préparer et vérifier la feuille de style de cet outil.',
    lancer: 'Copiez les deux fichiers dans le même dossier, puis ouvrez index.html. Inspectez la règle .grille. Pour Tailwind ou Bootstrap, partez ensuite du guide officiel de l’outil choisi, installez-le et vérifiez le CSS chargé.',
    attendu: 'Deux colonnes sur un écran large et une colonne sous 36rem. Retirer le lien CSS fait disparaître la grille : la cause est observable.',
    erreur: 'Un CDN ou une commande d’installation de démonstration n’est pas automatiquement un choix de production. Décidez selon version, taille, mise à jour et contraintes du projet.',
    exercice: 'Ajoutez un état :focus-visible à un bouton de la page et vérifiez son contraste au clavier.',
    correction: 'Une règle button:focus-visible { outline: 3px solid #1d4ed8; outline-offset: 2px; } rend la position visible sans dépendre de la souris.',
    source: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Getting_started'
  },
  {
    id: 'python-chemins-erreurs', domaine: 'python', titre: 'Lire un fichier sans confondre chemin et contenu', niveau: 2,
    situation: 'Le script fonctionne depuis son dossier mais échoue depuis un autre terminal. Il lit un nom relatif sans dire à quel dossier il est relatif.',
    notion: 'Path(__file__).resolve().parent donne le dossier du script. Path.cwd() donne le dossier courant du processus. Utilisez le premier pour une ressource livrée avec le programme et le second quand la personne fournit un chemin relatif à sa position.',
    fichier: 'main.py', langage: 'Python',
    code: 'from pathlib import Path\nchemin = Path(__file__).resolve().parent / "note.txt"\ntry:\n    texte = chemin.read_text(encoding="utf-8")\nexcept FileNotFoundError:\n    print(f"Fichier absent : {chemin}")\nelse:\n    print(texte.strip())',
    second: 'from pathlib import Path\nprint("Dossier du terminal :", Path.cwd())\nprint("Dossier du script :", Path(__file__).resolve().parent)',
    detail: 'L’opérateur / de Path assemble deux morceaux de chemin. read_text décode en UTF-8 ; FileNotFoundError décrit une ressource absente. else ne s’exécute que si la lecture a réussi.',
    lancer: 'Placez main.py et note.txt contenant Bonjour dans le même dossier. Exécutez python3 main.py, puis lancez python3 sous-dossier/main.py depuis le parent ; sous Windows, py main.py.',
    attendu: 'Le contenu est lu dans les deux cas. Si note.txt est absent, le message donne le chemin cherché au lieu de faire croire à un fichier vide.',
    erreur: 'Attraper toute Exception et afficher « rien à lire » cacherait aussi une erreur de permission ou de décodage.',
    exercice: 'Que change Path.cwd() lorsque la commande est lancée depuis le parent ? Que change Path(__file__).resolve().parent ?',
    correction: 'Path.cwd() devient le parent ; le dossier calculé depuis __file__ reste le dossier de main.py. C’est pourquoi le premier code retrouve note.txt.',
    source: 'https://docs.python.org/3/library/pathlib.html'
  },
  {
    id: 'java-fichier-classe-package', domaine: 'java', titre: 'Relier nom de fichier, classe et commande Java', niveau: 2,
    situation: 'javac refuse un programme dont la classe publique et le fichier ont des noms différents. Une fois compilé, java n’attend pas un nom de fichier .class.',
    notion: 'Un fichier source Java doit porter le nom de sa classe publique. javac compile en bytecode ; java lance la classe par son nom. Dans un projet avec package, le chemin et la commande doivent refléter ce package.',
    fichier: 'Bonjour.java', langage: 'Java',
    code: 'public class Bonjour {\n  static int doubler(int nombre) { return nombre * 2; }\n  public static void main(String[] args) {\n    System.out.println(doubler(4));\n  }\n}',
    second: '// Variante : src/exemple/Bonjour.java\npackage exemple;\npublic class Bonjour {\n  public static void main(String[] args) { System.out.println("Salut"); }\n}',
    detail: 'main est le point d’entrée. doubler renvoie un int réutilisable. Dans la variante, package exemple place la classe dans un espace nommé : javac -d out crée la bonne arborescence et java -cp out exemple.Bonjour la retrouve.',
    lancer: 'Premier cas : javac Bonjour.java puis java Bonjour. Variante depuis le parent de src : javac -d out src/exemple/Bonjour.java puis java -cp out exemple.Bonjour.',
    attendu: 'Le premier programme affiche 8 ; la variante affiche Salut. Vous lancez un nom de classe, pas Bonjour.class.',
    erreur: 'Renommer seulement le fichier sans renommer public class produit un diagnostic du compilateur ; lisez le nom qu’il attend.',
    exercice: 'Changez doubler en tripler et prédisez le résultat pour 4. Mettez ensuite la classe dans le package exemple.',
    correction: 'return nombre * 3 renvoie 12. Avec package exemple, le fichier vit sous src/exemple, la compilation place la classe sous out/exemple, et la commande utilise exemple.Bonjour.',
    source: 'https://dev.java/learn/getting-started/'
  },
  {
    id: 'springboot-dto-frontiere', domaine: 'springboot', titre: 'Séparer requête, réponse publique et règle métier', niveau: 5,
    situation: 'Une API renvoie directement une entité de base et expose accidentellement un nouveau champ privé. Le contrat HTTP doit choisir ses champs.',
    notion: 'Un record de requête décrit les données reçues ; un record de réponse décrit ce qui peut sortir. Le contrôleur valide les entrées au bord, appelle le service et renvoie un statut cohérent. Ce petit exemple garde les données en mémoire pour isoler le contrat ; une vraie concurrence requiert une base et des contraintes.',
    fichier: 'src/main/java/com/example/demo/AtelierController.java', langage: 'Java',
    code: 'package com.example.demo;\nimport org.springframework.http.HttpStatus;\nimport org.springframework.web.bind.annotation.*;\nrecord NouveauLivre(String titre) {}\nrecord LivrePublic(long id, String titre) {}\n@RestController\nclass AtelierController {\n  @PostMapping("/livres") @ResponseStatus(HttpStatus.CREATED)\n  LivrePublic creer(@RequestBody NouveauLivre entree) {\n    if (entree == null || entree.titre() == null || entree.titre().isBlank())\n      throw new IllegalArgumentException("titre requis");\n    return new LivrePublic(1, entree.titre().trim());\n  }\n}',
    second: 'package com.example.demo;\nimport org.springframework.http.HttpStatus;\nimport org.springframework.web.bind.annotation.*;\n@RestControllerAdvice\nclass Erreurs {\n  @ExceptionHandler(IllegalArgumentException.class) @ResponseStatus(HttpStatus.BAD_REQUEST)\n  String invalide(IllegalArgumentException e) { return e.getMessage(); }\n}',
    detail: 'NouveauLivre reçoit titre ; LivrePublic ne contient que id et titre. @RequestBody lit le JSON et @ResponseStatus annonce 201. Le conseil d’erreur transforme une entrée invalide en 400 ; aucune entité interne n’est sérialisée.',
    lancer: 'Générez un projet Maven Java sur Spring Initializr avec Spring Web et le paquet com.example.demo. Gardez DemoApplication.java généré, créez les deux classes dans des fichiers séparés sous src/main/java/com/example/demo, puis lancez ./mvnw spring-boot:run (mvnw.cmd sous Windows). Testez POST /livres avec un JSON valide puis {}.',
    attendu: 'Le JSON valide reçoit 201 avec id et titre ; {} reçoit 400 avec titre requis. Le service de démonstration ne sauvegarde rien entre deux appels.',
    erreur: 'Retourner directement un objet de persistance révèle potentiellement des colonnes internes ; définissez un DTO public et testez son JSON.',
    exercice: 'Ajoutez un champ interne secret à une classe de stockage fictive et prouvez qu’il ne se retrouve pas dans LivrePublic.',
    correction: 'Seuls id et titre sont construits dans LivrePublic. Le champ secret ne peut pas sortir par cette réponse si vous n’en modifiez pas le contrat.',
    source: 'https://spring.io/guides/gs/rest-service'
  },
  {
    id: 'cpp-compilation-liaison', domaine: 'cpp', titre: 'Compiler deux fichiers et comprendre l’édition de liens', niveau: 3,
    situation: 'main.cpp appelle une fonction déclarée, mais la compilation d’un seul fichier échoue à la liaison : le corps de la fonction est dans calcul.cpp.',
    notion: 'Le compilateur vérifie chaque traduction ; l’éditeur de liens assemble les définitions nécessaires. Un en-tête déclare l’interface, un .cpp définit la fonction, et la commande de construction doit inclure les deux fichiers source.',
    fichier: 'calcul.hpp, calcul.cpp et main.cpp', langage: 'C++',
    code: '// calcul.hpp\n#pragma once\nint doubler(int nombre);\n\n// calcul.cpp\n#include "calcul.hpp"\nint doubler(int nombre) { return nombre * 2; }',
    second: '// main.cpp\n#include <iostream>\n#include "calcul.hpp"\nint main() {\n  std::cout << doubler(4) << "\\n";\n}',
    detail: 'main.cpp connaît la signature grâce à calcul.hpp. Le corps vit une seule fois dans calcul.cpp. #pragma once évite d’inclure deux fois la déclaration dans une unité de traduction ; il ne remplace pas l’édition de liens.',
    lancer: 'Créez trois fichiers séparés : copiez la partie après « // calcul.hpp » dans calcul.hpp, la partie après « // calcul.cpp » dans calcul.cpp, et le second bloc dans main.cpp. Sous Linux : g++ -std=c++20 -Wall -Wextra main.cpp calcul.cpp -o demo puis ./demo. Sous macOS, remplacez g++ par clang++. Sous Windows MSVC : cl /EHsc main.cpp calcul.cpp.',
    attendu: 'Le programme affiche 8. Compiler uniquement main.cpp provoque une erreur de lien, même si les deux fichiers existent sur le disque.',
    erreur: 'Copier la définition non inline dans l’en-tête puis l’inclure partout peut produire des définitions multiples. Séparez déclaration et définition pour ce cas.',
    exercice: 'Ajoutez tripler(int) dans l’en-tête et calcul.cpp, puis appelez-la depuis main.cpp.',
    correction: 'Déclarez int tripler(int nombre); dans calcul.hpp, définissez return nombre * 3; dans calcul.cpp, recompilez les deux .cpp et observez 12 pour tripler(4).',
    source: 'https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html'
  },
  {
    id: 'csharp-projet-programme', domaine: 'csharp', titre: 'Faire correspondre projet .NET, fichier et exécution', niveau: 2,
    situation: 'Un fichier Program.cs isolé semble correct mais dotnet run ne trouve aucun projet. Le SDK attend aussi un .csproj ou une commande de création adaptée.',
    notion: 'Le fichier .csproj décrit la cible du projet et ses dépendances ; Program.cs contient les instructions. dotnet new console crée ensemble un projet et une amorce. Le code peut ensuite lire et contrôler une entrée sans supposer qu’elle est toujours présente.',
    fichier: 'Program.cs', langage: 'C#',
    code: 'Console.Write("Entrez une quantité : ");\nstring? texte = Console.ReadLine();\nif (!int.TryParse(texte, out int quantite) || quantite < 0) {\n    Console.Error.WriteLine("Quantité invalide");\n    return;\n}\nConsole.WriteLine($"Double : {quantite * 2}");',
    second: '// Après dotnet new console -n atelier --output .\n// Le SDK crée atelier.csproj : gardez sa version cible.\n// Vérifiez-la avec dotnet --version et dotnet run.',
    detail: 'ReadLine peut renvoyer null ; TryParse rend la conversion explicite et évite une exception sur une saisie ordinaire invalide. out quantite reçoit l’entier après succès. Console.Error sépare le diagnostic du résultat normal.',
    lancer: 'Dans un dossier vide, exécutez dotnet new console -n atelier --output ., remplacez Program.cs par le premier bloc, puis dotnet run. Ne recopiez pas un framework .NET inventé dans le .csproj généré.',
    attendu: 'Pour 4, la sortie est Double : 8. Pour abc ou -1, le programme affiche Quantité invalide et ne calcule pas.',
    erreur: 'int.Parse sur une saisie non validée lève FormatException. TryParse exprime un échec de saisie attendu sans faire passer la panne pour un résultat.',
    exercice: 'Ajoutez une borne maximale 100 et expliquez comment vous testerez 100 puis 101.',
    correction: 'Ajoutez || quantite > 100 dans la condition. 100 est accepté ; 101 affiche l’erreur. Les valeurs limites prouvent la règle plus clairement qu’un seul cas heureux.',
    source: 'https://learn.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code'
  },
  {
    id: 'php-formulaire-sortie', domaine: 'php', titre: 'Recevoir un formulaire et échapper la sortie', niveau: 3,
    situation: 'Un visiteur envoie du texte contenant <script>. Si la page le recopie tel quel en HTML, ce texte peut devenir du code dans le navigateur.',
    notion: '$_POST contient des données externes. trim nettoie les espaces périphériques mais ne valide pas toutes les règles. htmlspecialchars protège l’insertion dans un contexte de texte HTML ; ce n’est pas une protection universelle pour SQL, URL ou JavaScript.',
    fichier: 'index.php', langage: 'PHP',
    code: '<?php\n$nom = trim((string)($_POST["nom"] ?? ""));\n$erreur = $_SERVER["REQUEST_METHOD"] === "POST" && $nom === "" ? "Nom requis" : "";\n?>\n<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Accueil</title></head><body>\n<main><h1>Bienvenue</h1>\n<form method="post"><label>Votre nom <input name="nom" required></label><button>Valider</button></form>\n<?php if ($erreur): ?><p role="alert"><?= htmlspecialchars($erreur, ENT_QUOTES, "UTF-8") ?></p><?php endif; ?>\n<?php if ($nom !== ""): ?><p>Bonjour <?= htmlspecialchars($nom, ENT_QUOTES, "UTF-8") ?></p><?php endif; ?>\n</main></body></html>',
    second: '// Dans un contexte SQL, utilisez une requête préparée PDO :\n$requete = $pdo->prepare("SELECT id FROM membres WHERE nom = :nom");\n$requete->execute(["nom" => $nom]);',
    detail: 'Le formulaire poste vers la page courante. Le ?? fournit un texte vide quand la clé manque. ENT_QUOTES protège aussi les guillemets dans un contexte HTML. Le deuxième bloc montre une autre frontière : SQL demande des paramètres, pas htmlspecialchars.',
    lancer: 'Dans le dossier contenant index.php, exécutez php -S 127.0.0.1:8000 puis ouvrez http://127.0.0.1:8000/index.php. Le serveur intégré sert uniquement à cet essai local.',
    attendu: 'Un nom normal apparaît. Un texte contenant des balises est affiché comme texte ; il ne devient pas un élément HTML exécuté.',
    erreur: 'Le champ required se contourne par une requête directe : le serveur doit aussi refuser ou traiter proprement une valeur vide selon son contrat.',
    exercice: 'Ajoutez une limite de 80 caractères côté serveur et un message explicite au lieu de tronquer silencieusement.',
    correction: 'Après lecture de $nom, contrôlez sa longueur avec mb_strlen si l’extension est disponible, ou une stratégie de validation adaptée à l’encodage ; une longueur excessive produit un message d’erreur. La limite HTML seule ne protège pas le serveur.',
    source: 'https://www.php.net/manual/en/function.htmlspecialchars.php'
  }
];

function fabriquer(item) {
  const section = (type, titre, contenu, autres = {}) => ({ type, titre, contenu, ...autres });
  const sections = [
    section('texte', 'Partir d’un défaut réel', item.situation),
    section('texte', 'Les éléments indispensables', item.notion),
    section('code', `Premier exemple : ${item.fichier}`, item.code, { langage: item.langage, legende: `Fichier ou groupe de fichiers : ${item.fichier}` }),
    section('texte', 'Lire le code et suivre les valeurs', item.detail),
    section('code', item.id === 'springboot-dto-frontiere' ? 'Fichier complet : src/main/java/com/example/demo/Erreurs.java' : 'Deuxième exemple ou variation', item.second, { langage: item.langage }),
    section('texte', 'Préparer et lancer', item.lancer),
    section('texte', 'Observer le résultat', item.attendu),
    section('texte', 'Comprendre un échec fréquent', item.erreur),
    section('exercice', 'À vous de jouer avant le corrigé', item.exercice, { indice: item.detail.split('.')[0] + '.' }),
    section('solution', 'Corrigé raisonné', item.correction),
    { type: 'liens', titre: 'Documentation officielle', elements: [{ label: 'Vérifier la notion à la source', url: item.source }] }
  ];
  return {
    id: item.id, domaine: item.domaine, categorie: item.niveau > 3 ? 'Approfondissement' : 'Fondations pratiques',
    titre: item.titre, resume: item.situation, niveau: item.niveau > 3 ? 'Intermédiaire → professionnel' : 'Fondamental → autonome',
    niveauPedagogique: item.niveau, tempsEstime: 35, sections, associes: [],
    sessions: [
      { id: 'comprendre', titre: 'Comprendre le défaut', duree: '5 min', activite: 'Expliquez le défaut sans regarder le code.', sections: [0] },
      { id: 'observer', titre: 'Lire les deux exemples', duree: '10 min', activite: 'Prédisez le résultat de chaque bloc.', sections: [2] },
      { id: 'executer', titre: 'Lancer dans le bon dossier', duree: '10 min', activite: 'Suivez les fichiers et commandes exacts.', sections: [5] },
      { id: 'pratiquer', titre: 'Modifier seul', duree: '7 min', activite: 'Faites la variation avant le corrigé.', sections: [8] },
      { id: 'verifier', titre: 'Comparer le raisonnement', duree: '3 min', activite: 'Comparez votre résultat au corrigé.', sections: [9] }
    ],
    maturiteEditoriale: 'enriched', provenance: 'redaction-specifique'
  };
}

module.exports = exemples.map(fabriquer);
