'use strict';
const fichiersSource = 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Environment_setup/Dealing_with_files';
const webSource = 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works';
const terminalSource = 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Environment_setup/Command_line';
const q = (id, question, choix, correct, explication) => ({ id, question, choix, correct, explication });
const lecons = [
  {
    id: 'zero-ordinateur', titre: 'Comprendre ce que fait un ordinateur',
    objectif: 'Distinguer ce que vous demandez, ce que la machine exécute et ce qu’elle conserve.',
    situation: 'Vous écrivez une liste de courses, puis vous fermez l’application. À la réouverture, certains mots ont disparu. La machine a affiché votre texte, mais ne l’a pas nécessairement conservé.',
    probleme: 'Voir une information à l’écran ne prouve pas qu’elle est enregistrée. Pour développer, il faut distinguer l’action, les données manipulées et leur conservation.',
    analogie: 'Sur un bureau, une feuille sert à conserver une note ; votre espace de travail sert à la modifier. Cette comparaison aide à séparer stockage et travail en cours. Un ordinateur ne pense pas comme une personne : il suit des instructions.',
    modele: 'Une entrée arrive, des instructions la traitent, une sortie apparaît. Un programme est un ensemble d’instructions exécutées par l’ordinateur. Une donnée est une information manipulée : texte, nombre ou image. La mémoire de travail sert pendant l’exécution ; le stockage conserve notamment vos fichiers après fermeture.',
    vocabulaire: [['programme', 'Ensemble d’instructions que l’ordinateur peut exécuter.'], ['donnée', 'Information lue, produite ou modifiée par un programme.'], ['stockage', 'Support sur lequel une information peut être conservée après fermeture du programme.']],
    exemple: 'Entrée : vous tapez Bonjour\nTraitement : l’application place les lettres dans le document\nSortie : Bonjour apparaît à l’écran\nEnregistrement : vous demandez de conserver le document',
    anatomie: '« Entrée » désigne votre texte ; « traitement » désigne les actions de l’application. La sortie visible et l’enregistrement sont deux actions distinctes. Ce schéma décrit un fonctionnement ; ce n’est pas une commande à exécuter.',
    execution: ['Ouvrez une application de notes déjà installée.', 'Écrivez Bonjour, puis utilisez son action Enregistrer si elle est proposée.', 'Fermez et rouvrez la note pour observer ce qui a été conservé. Certaines applications enregistrent automatiquement.'],
    resultat: 'Le texte enregistré réapparaît. Vous avez vérifié la conservation en rouvrant, pas seulement en regardant l’écran.',
    variation: 'Remplacez Bonjour par Bonsoir et recommencez. Identifiez précisément l’action qui conserve la modification.',
    incorrect: '« Le texte est affiché, donc il est sauvegardé. »',
    diagnostic: 'Vérifiez si l’application annonce une modification non enregistrée, puis rouvrez le document. Évitez d’éteindre la machine pour tester une sauvegarde.',
    exercice: 'Décrivez une action de votre quotidien sur ordinateur en séparant entrée, traitement, sortie et conservation. Utilisez un autre exemple que la note.',
    indice: 'Une calculatrice reçoit deux nombres, calcule puis affiche un résultat. Conserve-t-elle ce calcul après fermeture ?',
    correction: 'Pour une photo recadrée : l’entrée est la photo et le cadre choisi, le traitement retire les bords, la sortie est l’aperçu. Exporter ou enregistrer crée la version conservée. L’aperçu seul ne prouve pas que le fichier d’origine a changé.',
    transfert: 'Dans un formulaire de site, distinguez ce qui est tapé, ce qui est contrôlé et ce qui est réellement enregistré.',
    retenir: 'Une action visible et une donnée conservée sont différentes. Vérifier le résultat fait partie du travail.',
    attendre: 'Le fonctionnement électronique du processeur et les détails de la mémoire peuvent attendre.',
    source: webSource,
    questions: [q('entree', 'Dans une calculatrice, que représente le nombre tapé ?', ['Une entrée', 'Une sauvegarde', 'Le résultat'], 0, 'Le nombre est fourni au programme avant le calcul : c’est une entrée.'), q('sauve', 'Quelle observation confirme qu’une note a été conservée ?', ['Elle est visible avant fermeture', 'Elle réapparaît après réouverture', 'Le clavier a répondu'], 1, 'La réouverture permet de vérifier la donnée conservée.')]
  },
  {
    id: 'zero-fichiers', titre: 'Créer un fichier et retrouver son chemin',
    objectif: 'Ranger un fichier dans un dossier et expliquer son nom, son extension et son emplacement.',
    situation: 'Vous avez deux documents nommés notes.txt. Modifier le premier ne change pas le second : ils peuvent se trouver dans des dossiers différents.',
    probleme: 'Un nom seul ne suffit pas toujours pour retrouver un document. Le programme doit connaître son emplacement.',
    analogie: 'Un dossier ressemble à une chemise de classement. Un chemin ressemble à une suite d’indications pour la retrouver. Deux chemises peuvent contenir une feuille du même nom.',
    modele: 'Un fichier est un ensemble de données enregistré sous un nom. Un dossier regroupe des fichiers et d’autres dossiers. Une extension est la fin du nom après le dernier point, comme .txt. Elle indique habituellement un format, mais renommer la fin ne convertit pas les données. Un chemin décrit comment atteindre le fichier.',
    vocabulaire: [['fichier', 'Données enregistrées sous un nom.'], ['dossier', 'Emplacement regroupant des fichiers et éventuellement des sous-dossiers.'], ['extension', 'Fin d’un nom comme .txt, habituellement associée à un format.'], ['chemin', 'Indications successives pour retrouver un fichier ou un dossier.']],
    exemple: 'apprentissage/\n  notes.txt\n  images/\n    portrait.png',
    anatomie: 'apprentissage est le dossier de départ. images est son sous-dossier. Depuis apprentissage, images/portrait.png indique le fichier portrait.png. Le caractère / sépare les étapes de ce chemin ; Windows affiche souvent \\ dans ses chemins.',
    execution: ['Dans votre dossier Documents, créez le dossier apprentissage avec le gestionnaire de fichiers.', 'Avec une application de texte simple, enregistrez notes.txt dans ce dossier.', 'Fermez le document, retrouvez son dossier puis ouvrez notes.txt.'],
    resultat: 'Vous pouvez retrouver notes.txt sans passer par la liste des fichiers récents.',
    variation: 'Créez un sous-dossier essais et copiez-y notes.txt. Vous avez deux fichiers indépendants avec le même nom.',
    incorrect: 'Renommer portrait.png en portrait.txt pour transformer une photo en texte.',
    diagnostic: 'Regardez le nom complet et le dossier. L’extension n’est qu’une indication : changer le nom ne réécrit pas le contenu. Activez l’affichage des extensions si elles sont masquées.',
    exercice: 'Dans le dossier apprentissage, le dossier essais contient resultat.txt. Écrivez le chemin depuis apprentissage, puis expliquez ce qui arrive si vous déplacez resultat.txt directement dans apprentissage.',
    indice: 'Listez les dossiers traversés, puis le nom du fichier.',
    correction: 'Le chemin initial est essais/resultat.txt. Après déplacement, il devient resultat.txt depuis apprentissage. L’ancien chemin ne pointe plus au même emplacement ; le contenu n’a pas été converti.',
    transfert: 'Une image manquante dans une page est souvent un chemin incorrect ou un nom dont les majuscules ne correspondent pas.',
    retenir: 'Nom, extension et emplacement décrivent trois aspects différents du fichier.',
    attendre: 'Les permissions et les liens entre fichiers seront abordés lorsque vous utiliserez le terminal.',
    source: fichiersSource,
    questions: [q('chemin', 'Depuis apprentissage, comment atteindre portrait.png dans images ?', ['portrait.png/images', 'images/portrait.png', 'apprentissage.png'], 1, 'On traverse images avant d’atteindre portrait.png.'), q('extension', 'Renommer photo.png en photo.txt transforme-t-il la photo en texte ?', ['Oui', 'Non'], 1, 'Le nom change, pas le format réel des données.')]
  },
  {
    id: 'zero-programme', titre: 'Passer d’un texte source à un résultat visible',
    objectif: 'Distinguer l’outil qui modifie un fichier de celui qui l’interprète.',
    situation: 'Vous voulez écrire votre nom en grand sur une page. Le texte que vous écrivez et le résultat visible seront ouverts dans deux applications différentes.',
    probleme: 'Un traitement de texte peut ajouter une mise en forme invisible. Pour écrire un fichier de site, nous voulons maîtriser le texte exact enregistré.',
    analogie: 'Une partition décrit des notes ; l’instrument produit le son. De même, un texte source décrit quelque chose à interpréter. Cette analogie ne signifie pas que tous les langages fonctionnent de la même façon.',
    modele: 'Un éditeur de code modifie du texte brut, sans mise en forme de traitement de texte. Un navigateur affiche des pages web. Le code source est le texte écrit pour décrire une structure ou des instructions. Un langage fixe les règles de ce texte. HTML décrit la structure d’une page ; JavaScript permet notamment d’écrire des instructions et des calculs.',
    vocabulaire: [['éditeur de code', 'Application conçue pour écrire et modifier le texte source.'], ['navigateur', 'Application qui permet de consulter les pages du Web.'], ['code source', 'Texte écrit pour décrire une structure ou des instructions dans un langage.'], ['HTML', 'Langage de balisage qui décrit les parties d’un document.'], ['balise', 'Marque entre < et > qui délimite ou indique une partie HTML.']],
    exemple: '<h1>Mon premier titre</h1>', langage: 'HTML',
    anatomie: '<h1> commence un titre principal. Mon premier titre est le texte à afficher. </h1> ferme le titre : la barre / indique la fermeture. C’est un fragment de page ; la structure complète viendra dans les fondations HTML.',
    execution: ['Dans un éditeur de texte brut, créez accueil.html dans apprentissage.', 'Écrivez le fragment puis enregistrez.', 'Ouvrez le fichier avec votre navigateur. Modifiez le texte dans l’éditeur, enregistrez puis rechargez la page.'],
    resultat: 'Le navigateur affiche un titre. Il interprète les balises au lieu de les montrer comme texte ordinaire.',
    variation: 'Remplacez Mon premier titre par votre prénom. Les balises restent les mêmes, seul le contenu change.',
    incorrect: 'Modifier accueil.html dans l’éditeur, puis attendre que le navigateur affiche automatiquement la nouvelle version.',
    diagnostic: 'Vérifiez que vous avez enregistré le bon fichier et rechargé le navigateur. Vérifiez aussi que son vrai nom n’est pas accueil.html.txt.',
    exercice: 'Écrivez un titre différent et décrivez les trois actions nécessaires pour voir la modification dans le navigateur.',
    indice: 'Pensez à l’édition, au fichier conservé, puis à l’affichage.',
    correction: 'Écrire <h1>Mon carnet</h1>, enregistrer accueil.html dans l’éditeur puis recharger ce même fichier dans le navigateur. Le navigateur ne lit pas automatiquement les modifications qui sont encore seulement dans l’éditeur.',
    transfert: 'Ce cycle modifier → enregistrer → observer sera réutilisé pour les styles et les programmes.',
    retenir: 'L’éditeur modifie le texte source ; le navigateur interprète la page. HTML n’est pas un langage de calcul.',
    attendre: 'Les outils qui préparent automatiquement le code et les frameworks peuvent attendre.',
    source: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Your_first_website/Creating_the_content',
    questions: [q('editeur', 'Où modifiez-vous le texte source de accueil.html ?', ['Dans la barre d’adresse', 'Dans l’éditeur de texte', 'Dans le nom du dossier'], 1, 'L’éditeur modifie le contenu du fichier.'), q('fermeture', 'Dans </h1>, que signale la barre / ?', ['Le début du titre', 'La fermeture du titre', 'Un dossier'], 1, 'Dans cette balise HTML, / indique la fermeture.')]
  },
  {
    id: 'zero-web', titre: 'Suivre le trajet d’une page sur Internet',
    objectif: 'Expliquer qui demande une page, à quelle adresse et qui lui répond.',
    situation: 'Votre fichier accueil.html s’ouvre sans connexion. Pourtant, une page hébergée chez quelqu’un d’autre peut être inaccessible quand la connexion est coupée.',
    probleme: 'Une page locale est déjà sur votre appareil. Une page distante nécessite généralement un échange avec un autre ordinateur.',
    analogie: 'Une demande au guichet comporte une destination et un objet. Le guichet répond avec un document ou une explication du refus. Cela aide à séparer demande et réponse, sans décrire tous les transports du réseau.',
    modele: 'Internet relie des réseaux d’ordinateurs. Le Web est un usage d’Internet pour échanger notamment des pages. Le client est le programme qui demande, ici le navigateur. Le serveur est un programme qui reçoit des demandes et répond, généralement sur un autre ordinateur. Une URL est l’adresse d’une ressource. Une requête est une demande envoyée ; une réponse est le message retourné.',
    vocabulaire: [['Internet', 'Réseau reliant de nombreux réseaux d’ordinateurs.'], ['client', 'Programme qui envoie une demande.'], ['serveur', 'Programme qui reçoit des demandes et leur répond.'], ['URL', 'Adresse qui identifie une ressource et comment y accéder.'], ['requête', 'Message envoyé pour demander une action ou une ressource.'], ['réponse', 'Message envoyé en retour à une requête.']],
    exemple: 'https://example.com/carnet\n\nNavigateur → demande /carnet → serveur\nNavigateur ← page ou erreur ← serveur',
    anatomie: 'https indique le mode d’échange sécurisé. example.com est le nom de l’hôte à joindre. /carnet est le chemin demandé sur cet hôte ; il ne correspond pas forcément à un fichier sur disque.',
    execution: ['Ouvrez une page web connue.', 'Repérez le nom du site dans la barre d’adresse.', 'Comparez avec accueil.html ouvert depuis votre dossier : son adresse commence généralement par file:.'],
    resultat: 'Vous distinguez une ressource locale d’une adresse distante sans supposer que tout affichage utilise Internet.',
    variation: 'Imaginez la même demande envoyée à une mauvaise adresse : elle peut atteindre le mauvais serveur ou ne jamais obtenir de réponse.',
    incorrect: '« Une page ne s’affiche pas ; mon fichier local a forcément été effacé. »',
    diagnostic: 'Distinguez problème de connexion, mauvaise adresse et réponse d’erreur du serveur. Une erreur 404 signifie que le serveur ne trouve pas la ressource demandée, pas nécessairement que votre connexion est coupée.',
    exercice: 'Expliquez le trajet d’une demande de page avec les mots client, URL, requête, serveur et réponse, puis nommez un point où le trajet peut échouer.',
    indice: 'Commencez par le navigateur et terminez par le message qu’il reçoit.',
    correction: 'Le navigateur client utilise l’URL pour adresser une requête au serveur. Celui-ci renvoie une réponse, par exemple la page ou une erreur. Si le réseau est coupé, la demande peut ne pas atteindre le serveur ; si le chemin est faux, le serveur peut répondre 404.',
    transfert: 'Quand une application charge des données, on suit le même trajet pour localiser le problème.',
    retenir: 'Client et serveur sont des rôles de programmes. L’adresse, la demande et la réponse sont distinctes.',
    attendre: 'Le détail des paquets réseau, des certificats et de la résolution des noms viendra plus tard.',
    source: webSource,
    questions: [q('client', 'Quel programme joue le rôle de client quand vous ouvrez un site ?', ['Le navigateur', 'Le dossier Documents', 'Le clavier'], 0, 'Le navigateur envoie la demande.'), q('reponse', 'Le serveur répond 404. Qu’avez-vous déjà reçu ?', ['Aucun échange réseau', 'Une réponse indiquant une ressource introuvable', 'La preuve d’un fichier local effacé'], 1, '404 est un statut dans une réponse ; un serveur a donc répondu.')]
  },
  {
    id: 'zero-terminal', titre: 'Lire une commande avant de l’exécuter',
    objectif: 'Utiliser une commande de lecture et distinguer commande, sortie et programme en cours.',
    situation: 'Un guide vous demande d’ouvrir un terminal. Vous n’avez pas besoin de quitter les fenêtres : c’est une autre façon de demander une action à l’ordinateur.',
    probleme: 'Copier une ligne sans comprendre son action et son dossier de départ peut produire un résultat inattendu.',
    analogie: 'Dans un restaurant, vous pouvez montrer un plat ou prononcer son nom. Une interface graphique et une commande sont deux moyens d’exprimer une demande ; certaines commandes font toutefois des actions impossibles à annuler.',
    modele: 'Un terminal est une fenêtre d’échange textuel. Une commande est une instruction que vous y saisissez. Un interpréteur de commandes, aussi appelé shell, lit cette instruction : PowerShell sur beaucoup de postes Windows, Bash ou Zsh dans d’autres environnements. Un processus est un programme en cours d’exécution. Sa sortie est le texte qu’il produit.',
    vocabulaire: [['terminal', 'Fenêtre permettant de saisir des commandes et de lire leurs sorties.'], ['commande', 'Instruction saisie pour demander une action.'], ['shell', 'Programme qui interprète les commandes, par exemple PowerShell ou Bash.'], ['processus', 'Programme en cours d’exécution.']],
    exemple: '# PowerShell (Windows)\nGet-Location\n\n# Bash ou Zsh (Linux/macOS)\npwd', langage: 'Terminal — choisir sa ligne',
    anatomie: 'Les lignes commençant par # sont des commentaires explicatifs dans ces interpréteurs. Get-Location et pwd affichent votre dossier courant. Exécutez seulement la commande correspondant à votre interpréteur ; le symbole d’invite affiché avant la saisie ne fait pas partie de la commande.',
    execution: ['Ouvrez le terminal de votre système et repérez son interpréteur.', 'Tapez la commande de lecture adaptée, puis appuyez sur Entrée.', 'Lisez le chemin affiché. Comparez-le au dossier visible dans votre gestionnaire de fichiers.'],
    resultat: 'Un chemin apparaît. Aucun fichier n’a besoin d’être modifié pour connaître le dossier courant.',
    variation: 'Fermez cette fenêtre puis ouvrez-en une autre. Vérifiez le dossier au lieu de supposer qu’il est identique.',
    incorrect: 'Coller le symbole $ ou > de l’invite avec la commande d’un tutoriel.',
    diagnostic: 'Relisez la commande exacte, le nom de l’interpréteur et le dossier courant. Un message « command not found » signifie que le nom demandé n’a pas été trouvé, pas que votre ordinateur est cassé.',
    exercice: 'Écrivez la commande de lecture utilisée sur votre poste, la sortie observée et ce que cette sortie vous apprend. Sur téléphone, prédisez la sortie attendue sans prétendre l’avoir exécutée.',
    indice: 'La sortie doit ressembler à un chemin, pas au contenu d’un fichier.',
    correction: 'Get-Location dans PowerShell affiche l’emplacement courant ; pwd dans Bash/Zsh affiche son chemin. La valeur exacte dépend de votre poste. Décrire « je me trouve dans mon dossier personnel » est utile ; inventer un chemin exécuté ne l’est pas.',
    transfert: 'Avant une installation ou un lancement de programme, vérifiez dans quel dossier la commande agira.',
    retenir: 'Une commande et sa sortie sont différentes. Lire le dossier courant est une première action sans modification.',
    attendre: 'Les redirections, les scripts et les permissions avancées ne sont pas nécessaires pour cette première commande.',
    source: terminalSource,
    questions: [q('pwd', 'Que permet de connaître pwd dans Bash ?', ['Le mot de passe', 'Le dossier courant', 'Le contenu de tous les fichiers'], 1, 'pwd affiche le chemin du dossier courant.'), q('processus', 'Un programme lancé et encore en fonctionnement est…', ['un processus', 'une extension', 'une URL'], 0, 'Un processus est une exécution en cours d’un programme.')]
  },
  {
    id: 'zero-outils', titre: 'Installer seulement l’outil dont vous avez besoin',
    objectif: 'Choisir une source officielle et vérifier que l’outil installé répond.',
    situation: 'Pour modifier accueil.html, un éditeur et un navigateur suffisent. Un guide de programmation côté serveur demande en plus Node.js. Ces besoins ne sont pas les mêmes.',
    probleme: 'Installer une longue liste d’outils avant de connaître leur rôle rend les erreurs difficiles à comprendre.',
    analogie: 'On choisit un tournevis pour une vis donnée, puis on vérifie son empreinte. On ne remplit pas d’abord toute une caisse d’outils pour pouvoir ouvrir une porte.',
    modele: 'Installer signifie rendre un programme disponible sur votre poste. Un environnement d’exécution, parfois appelé runtime, exécute un langage : Node.js exécute du JavaScript en dehors du navigateur. Un compilateur traduit un programme vers une autre forme avant son exécution, par exemple pour certains projets C++. Vous n’en avez pas besoin pour lire une première page HTML.',
    vocabulaire: [['installation', 'Opération qui rend un programme et ses fichiers disponibles sur le poste.'], ['environnement d’exécution', 'Logiciel qui permet d’exécuter un programme écrit dans un langage.'], ['runtime', 'Nom anglais pour environnement d’exécution.'], ['compilateur', 'Programme qui traduit du code source vers une autre forme avant utilisation.'], ['PATH', 'Liste d’emplacements dans lesquels l’interpréteur cherche les programmes demandés par leur nom.']],
    exemple: 'node --version', langage: 'Terminal — après installation de Node.js',
    anatomie: 'node est le programme demandé. --version est une option lui demandant d’afficher sa version, puis de terminer. Cette commande ne crée pas votre projet et n’exécute pas votre fichier de code.',
    execution: ['Si votre prochaine leçon nécessite Node.js, ouvrez son site officiel via Préparer mon poste.', 'Choisissez les instructions pour votre système et suivez-les.', 'Rouvrez le terminal, puis demandez node --version. Pour HTML seul, gardez simplement l’éditeur et le navigateur.'],
    resultat: 'Une version apparaît si le programme est installé et trouvable. Le numéro varie ; recopiez celui de votre poste.',
    variation: 'Si le nom n’est pas trouvé, vérifiez l’installation et rouvrez le terminal avant de changer plusieurs réglages.',
    incorrect: 'Installer un programme depuis une publicité ou exécuter une commande d’installation copiée sans vérifier sa source.',
    diagnostic: 'Comparez l’adresse du site officiel et le système choisi. Un programme installé peut rester introuvable dans un terminal ouvert avant l’installation ; la liste PATH de ce terminal peut être ancienne.',
    exercice: 'Choisissez l’outil nécessaire à votre prochaine activité, expliquez son rôle et écrivez comment vous vérifierez qu’il est disponible.',
    indice: 'Pour modifier une page, pensez à l’éditeur. Pour exécuter JavaScript hors navigateur, pensez à Node.js.',
    correction: 'Pour accueil.html, j’ouvre mon éditeur et j’enregistre un fichier : je vérifie en le rouvrant. Pour un futur programme Node.js, je prends les instructions officielles adaptées au poste, puis node --version vérifie que la commande répond. Le besoin détermine l’installation.',
    transfert: 'Dans un projet d’équipe, noter l’outil et sa version permet de comparer deux postes qui se comportent différemment.',
    retenir: 'Un outil répond à un besoin précis. Vérifiez son origine et son fonctionnement après installation.',
    attendre: 'Les gestionnaires de versions et la configuration détaillée de PATH peuvent attendre un besoin concret.',
    source: 'https://nodejs.org/en/learn/getting-started/how-to-install-nodejs',
    questions: [q('html', 'Pour une page HTML locale, faut-il d’abord installer Node.js ?', ['Oui, toujours', 'Non, un éditeur et un navigateur suffisent'], 1, 'Le navigateur peut interpréter la page HTML locale.'), q('version', 'Que vérifie node --version ?', ['Que le programme node répond et sa version', 'Que tout votre code fonctionne', 'Que votre site est publié'], 0, 'La disponibilité de la commande ne prouve ni la qualité du code ni son déploiement.')]
  },
  {
    id: 'zero-erreurs', titre: 'Utiliser une erreur pour choisir quoi vérifier',
    objectif: 'Recopier une erreur, isoler sa cause probable et vérifier une correction à la fois.',
    situation: 'Vous ouvrez une page et une image manque. Changer toutes les lignes de la page rendrait le problème plus difficile à comprendre.',
    probleme: 'Une erreur décrit une observation, pas toujours sa cause exacte. Il faut relier le message à l’action qui vient d’être faite.',
    analogie: 'Un voyant de voiture signale un problème à examiner. Il ne vous demande pas de remplacer toutes les pièces. Un message d’erreur est lui aussi un point de départ pour un diagnostic.',
    modele: 'Une erreur est un écart entre le fonctionnement attendu et ce qui arrive. Un message d’erreur fournit des indices, par exemple un nom, un chemin ou un emplacement dans le code. Un diagnostic est une démarche pour tester une explication possible. La documentation décrit le comportement attendu d’un outil ou d’un langage.',
    vocabulaire: [['erreur', 'Écart ou échec observé pendant une action.'], ['diagnostic', 'Recherche d’une cause par des observations et des essais contrôlés.'], ['documentation', 'Explications de référence sur le fonctionnement et l’utilisation d’un outil.']],
    exemple: 'Attendu : ouvrir images/portrait.png\nObservé : fichier introuvable\nSur le disque : images/Portrait.png',
    anatomie: 'Le chemin attendu et le nom réel diffèrent par la majuscule. Selon le système et le serveur, cette différence compte. Comparer les noms exacts est une hypothèse testable.',
    execution: ['Recopiez l’action et le message exact dans votre note.', 'Comparez le chemin demandé au fichier présent.', 'Corrigez un seul nom ou un seul chemin, puis refaites la même action.'],
    resultat: 'Si la ressource s’ouvre, la correction explique l’observation. Sinon, conservez le nouveau message pour tester une autre cause.',
    variation: 'Si les noms correspondent déjà, vérifiez le dossier de départ. Ne répétez pas une correction qui n’a rien changé.',
    incorrect: 'Effacer le message ou réinstaller tous les outils pour faire disparaître une erreur de chemin.',
    diagnostic: 'Le symptôme concerne un fichier : commencez par son nom et son emplacement. Une réinstallation ne répare pas un mauvais chemin écrit dans une page.',
    exercice: 'Vous attendez notes.txt dans essais, mais il est dans apprentissage. Écrivez l’observation, une hypothèse, une correction et la vérification à effectuer.',
    indice: 'Vous pouvez soit déplacer le fichier, soit corriger le chemin ; choisissez une seule action.',
    correction: 'Observation : essais/notes.txt est introuvable. Hypothèse : le fichier est dans le dossier parent. Correction : utiliser notes.txt depuis apprentissage. Vérification : rouvrir ce chemin exact et contrôler le contenu. On n’a pas changé à la fois le programme et l’installation.',
    transfert: 'Un signalement utile à un collègue contient les étapes pour reproduire, le résultat attendu, le résultat observé et le message exact, sans secrets.',
    retenir: 'Observer, formuler une hypothèse, changer une chose, reproduire : l’erreur devient une information.',
    attendre: 'Les outils d’analyse de performance et de suivi de production viendront quand plusieurs composants interagiront.',
    source: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/What_went_wrong',
    questions: [q('changer', 'Pour tester une hypothèse, combien de causes indépendantes changez-vous à la fois ?', ['Une', 'Toutes celles possibles'], 0, 'Une modification isolée permet d’attribuer le résultat à cette modification.'), q('message', 'Quelle information est la plus utile pour diagnostiquer ?', ['Ça ne marche pas', 'L’action précise et le message exact', 'Le nombre de réinstallations'], 1, 'Une action reproductible et un message précis permettent de tester une cause.')]
  },
  {
    id: 'zero-sauvegarde', titre: 'Conserver son travail avant de le modifier',
    objectif: 'Distinguer enregistrement, copie de secours et historique de versions.',
    situation: 'Votre page fonctionne. Vous voulez changer son titre et sa disposition, mais garder la possibilité de comparer avec l’ancienne version.',
    probleme: 'Enregistrer remplace le contenu courant. Cela ne vous garantit pas un historique ni une copie si le disque tombe en panne.',
    analogie: 'Une photographie datée de votre travail permet de comparer deux états. Elle ne protège contre la perte de l’album que si une autre copie existe ailleurs.',
    modele: 'Enregistrer conserve l’état courant d’un fichier. Une sauvegarde est une copie de secours, idéalement sur un autre support. Un historique de versions conserve des états successifs. Git est un outil qui enregistre des versions choisies d’un projet. Un commit est un de ces enregistrements accompagné d’un message. Git local seul ne remplace pas une sauvegarde externe.',
    vocabulaire: [['sauvegarde', 'Copie de secours permettant de retrouver des données perdues.'], ['version', 'État d’un travail à un moment donné.'], ['Git', 'Outil permettant de conserver et comparer des versions d’un projet.'], ['commit', 'Enregistrement choisi dans l’historique Git, accompagné d’un message.']],
    exemple: 'apprentissage/accueil.html\nsauvegarde-avant-titre/accueil.html',
    anatomie: 'Ces deux chemins décrivent deux copies indépendantes pour un premier essai. Pour de nombreux changements, Git aide à éviter la multiplication de dossiers aux noms ambigus. Une copie sur le même disque ne protège pas contre une panne de ce disque.',
    execution: ['Enregistrez votre page puis copiez le dossier d’exercice avant de la modifier.', 'Changez le titre dans une seule copie.', 'Rouvrez les deux copies pour comparer. Gardez une sauvegarde sur un autre support pour vos travaux importants.'],
    resultat: 'Vous pouvez identifier l’ancien état et le nouvel état sans avoir à deviner le contenu précédent.',
    variation: 'Quand plusieurs changements deviennent difficiles à comparer, poursuivez avec la leçon Git : le besoin d’historique est maintenant concret.',
    incorrect: 'Croire que cliquer sur Enregistrer crée automatiquement une copie de toutes les versions précédentes.',
    diagnostic: 'Vérifiez les fonctions d’historique réelles de l’application et l’existence d’une copie indépendante. Ne supprimez pas votre seule copie pour tester la restauration.',
    exercice: 'Expliquez comment vous garderez votre page avant une modification et comment vous vérifierez que votre copie est utilisable.',
    indice: 'Une copie dont vous n’avez jamais vérifié l’ouverture reste une hypothèse de secours.',
    correction: 'J’enregistre la page, copie le dossier sous un nom explicite, puis ouvre la copie. Je vérifie son contenu avant de modifier l’original. Pour les changements répétés, j’apprendrai à faire des commits Git et à conserver aussi une copie externe.',
    transfert: 'Avant une mise en ligne ou un changement de données, préparer le retour à un état connu réduit le coût d’une erreur.',
    retenir: 'Enregistrer, conserver un historique et sauvegarder répondent à trois besoins différents.',
    attendre: 'Les branches partagées et les demandes de revue viendront avec le travail en équipe.',
    source: 'https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control',
    questions: [q('copie', 'Deux copies sur le même disque protègent-elles contre sa panne ?', ['Oui', 'Non'], 1, 'La panne du disque peut rendre les deux copies indisponibles.'), q('git', 'Quel problème Git aide-t-il principalement à résoudre ?', ['Conserver et comparer des versions', 'Réparer un disque', 'Accélérer Internet'], 0, 'Git conserve un historique choisi du projet ; il ne répare pas le matériel.')]
  }
];

module.exports = lecons.map((l, i) => {
  const section = (titre, contenu, profondeur = 0) => ({ type: 'texte', titre, contenu, profondeur });
  const sections = [
    section('Partir d’une situation concrète', l.situation), section('Comprendre le problème', l.probleme),
    section('Se représenter le fonctionnement', l.analogie), section('Nommer ce qui se passe', l.modele),
    { type: 'code', titre: 'Observer un exemple minimal', langage: l.langage || 'Schéma à lire', contenu: l.exemple },
    section('Lire chaque partie', l.anatomie), { type: 'liste', titre: 'Essayer pas à pas', contenu: l.execution },
    section('Vérifier le résultat attendu', l.resultat), section('Changer une chose', l.variation, 1),
    section('Reconnaître un mauvais raisonnement', l.incorrect), section('Diagnostiquer avant de corriger', l.diagnostic),
    { type: 'exercice', titre: 'Essayer sans le corrigé', contenu: l.exercice, indice: l.indice },
    { type: 'solution', titre: 'Comparer son raisonnement', contenu: l.correction },
    section('Réutiliser dans un projet', l.transfert, 1), section('Retenir maintenant', l.retenir),
    section('Garder pour plus tard', l.attendre, 1),
    { type: 'liens', titre: 'Vérifier à la source', elements: [{ label: 'Explication officielle', url: l.source }] }
  ];
  return { id: l.id, domaine: 'niveau-zero', categorie: 'Premiers repères', titre: l.titre, resume: l.objectif,
    tags: l.vocabulaire.map(([terme]) => terme), niveau: 'Niveau 0', niveauPedagogique: 0,
    maturiteEditoriale: 'enriched', provenance: 'redaction-specifique', tempsEstime: 15,
    prerequis: i ? [lecons[i - 1].id] : [], associes: i < lecons.length - 1 ? [lecons[i + 1].id] : ['html-document', 'git-cycle'],
    competences: [l.objectif], termesNouveaux: l.vocabulaire.map(([terme, definition]) => ({ terme, definition })),
    sections, evaluation: { version: 1, questions: l.questions },
    sessions: [
      { id: 'situation', titre: 'Comprendre le besoin', duree: '3 min', activite: 'Reliez la situation à une expérience vécue.', sections: [0] },
      { id: 'observer', titre: 'Observer l’exemple', duree: '3 min', activite: 'Expliquez chaque partie avant de continuer.', sections: [4] },
      { id: 'essayer', titre: 'Essayer sur son poste', duree: '4 min', activite: 'Faites la manipulation et notez le résultat.', sections: [6] },
      { id: 'pratiquer', titre: 'Répondre sans aide', duree: '3 min', activite: 'Écrivez votre réponse avant le corrigé.', sections: [11] },
      { id: 'verifier', titre: 'Comparer et retenir', duree: '2 min', activite: 'Comparez le raisonnement, puis faites le rappel actif.', sections: [12] }
    ]
  };
});
