'use strict';

// Cas supplémentaires ciblés pour les leçons que les ateliers ne couvrent pas
// par une variation utilisable. Les autres variations proviennent d'un atelier
// explicitement relié et renvoient à ses fichiers complets.
const propres = {
  'html-attributs': ['HTML', '<a href="/aide" aria-label="Lire l’aide sur les fichiers">Aide</a>\n<img src="images/schema.png" alt="Schéma des trois dossiers" width="320" height="180">', 'href donne la destination du lien ; src donne la ressource image. alt décrit l’information portée par l’image. Vérifiez les deux chemins dans le navigateur ; une image absente ne devient pas correcte en changeant seulement son texte alternatif.'],
  'html-texte-listes': ['HTML', '<main><h1>Préparer mon poste</h1><ol><li>Créer un dossier</li><li>Ouvrir l’éditeur</li><li>Enregistrer la page</li></ol></main>', 'ol exprime une suite dont l’ordre compte ; li désigne chaque étape. Copiez le bloc dans body d’une page complète et vérifiez que le lecteur voit 1, 2 et 3.'],
  'css-box-model': ['CSS', '.carte { width: 20rem; padding: 1rem; border: 2px solid; box-sizing: border-box; }\n/* La largeur extérieure reste 20rem hors marge. */', 'Le padding et la bordure entrent dans la largeur avec border-box. Retirez box-sizing dans DevTools pour voir la carte s’élargir ; ne devinez pas la largeur sur la seule valeur width.'],
  'js-variables': ['JavaScript', 'let essais = 0;\nessais += 1;\nconst etat = { valide: false };\netat.valide = true;\nconsole.log(essais, etat.valide); // 1 true', 'let autorise la réaffectation du nombre ; const garde la même référence d’objet, mais sa propriété peut changer. Exécutez dans la console ou avec node.'],
  'js-types': ['JavaScript', 'const entree = "42";\nconst nombre = Number(entree);\nconsole.log(typeof entree, typeof nombre, nombre + 1); // string number 43', 'Une saisie reste texte jusqu’à conversion. Changez entree en "abc" : Number produit NaN ; testez Number.isNaN avant de calculer avec une entrée réelle.'],
  'js-egalite': ['JavaScript', 'const codeRecu = "0";\nconsole.log(codeRecu === 0); // false\nconsole.log(Number(codeRecu) === 0); // true', '=== évite une conversion implicite. Convertissez après validation plutôt que d’utiliser == pour masquer que le type reçu est différent.'],
  'js-fonctions': ['JavaScript', 'function calculerTotal(prix, quantite) { return prix * quantite; }\nconst total = calculerTotal(5, 3);\nconsole.log(total); // 15', 'Les paramètres prix et quantite sont locaux à l’appel ; return rend 15 réutilisable. Remplacez return par console.log : total devient undefined.'],
  'js-json': ['JavaScript', 'const autreTexte = "{\\"id\\":1,\\"titre\\":\\"Web\\"}";\ntry { const livre = JSON.parse(autreTexte); console.log(livre.titre); }\ncatch (erreur) { console.error("JSON invalide", erreur.message); }', 'JSON.parse peut échouer si le texte est invalide ; le bloc catch annonce l’échec. JSON valide ne prouve pas que les propriétés métier existent.'],
  'js-event-loop': ['JavaScript', 'console.log("1 synchrone");\nqueueMicrotask(() => console.log("3 microtâche"));\nsetTimeout(() => console.log("4 minuterie"), 0);\nconsole.log("2 synchrone");', 'L’ordre observé est 1, 2, 3, 4 dans cet exemple. Le travail synchrone finit avant la microtâche, puis la minuterie ; 0 ne signifie pas exécution immédiate.'],
  'node-path': ['JavaScript', 'const path = require("node:path");\nconsole.log(path.resolve(process.cwd(), "notes", "a.txt"));\nconsole.log(path.join(__dirname, "notes", "a.txt"));', 'Lancez ce fichier depuis un autre dossier : la première ligne suit le terminal, la seconde reste liée au fichier source CommonJS. Choisissez explicitement le contrat voulu.'],
  'node-events': ['JavaScript', 'const { EventEmitter } = require("node:events");\nconst bus = new EventEmitter();\nbus.once("pret", valeur => console.log(valeur));\nbus.emit("pret", "une fois");\nbus.emit("pret", "deux fois");', 'once retire le gestionnaire après la première émission : seul une fois est affiché. Une émission sans gestionnaire d’erreur exige une attention particulière pour le nom error.'],
  'npm-dependances': ['Terminal', 'npm install express\nnpm install --save-dev nodemon\nnpm ls --depth=0\n# Relisez package.json et package-lock.json après ces commandes.', 'express devient une dépendance d’exécution ; nodemon sert au développement. npm ls montre les versions réellement présentes ; npm ci utilise ensuite le lockfile enregistré.'],
  'npm-semver': ['JSON', '{ "dependencies": { "express": "^4.22.3" } }', 'La plage dans package.json décrit des versions permises, le lockfile en choisit une exacte pour l’installation du projet. Examinez les deux fichiers avant de conclure que chaque poste utilise la même version.', '{ "dependencies": { "express": "~4.22.3" } }', 'Le tilde autorise les correctifs de la série 4.22 ; le caret peut autoriser une nouvelle version mineure compatible. Dans les deux cas, le lockfile retient la version réellement résolue.'],
  'express-statique': ['JavaScript', 'const express = require("express");\nconst path = require("node:path");\nconst app = express();\napp.use(express.static(path.join(__dirname, "public")));\napp.listen(3000);', 'Créez public/index.html puis lancez node server.js et ouvrez http://localhost:3000/. Le chemin part de __dirname, donc le service retrouve ses fichiers même si la commande est lancée depuis ailleurs.'],
  'frontend-choisir': ['HTML', '<!doctype html>\n<html lang="fr"><head><meta charset="utf-8"><title>Essai</title></head>\n<body><main><h1>Premier écran</h1><button type="button" id="action">Tester</button></main>\n<script>document.querySelector("#action").addEventListener("click", () => alert("Action reçue"));</script></body></html>', 'Cet écran s’ouvre sans framework ni build. Si le besoin ajoute plusieurs états et composants, comparez ensuite le coût d’une bibliothèque, mais mesurez d’abord la complexité réelle.', 'function Carte({ titre }) { return <article><h2>{titre}</h2></article>; }\n// JSX dans src/App.jsx d’un projet React généré avec Vite.', 'Le second exemple demande une chaîne de build et un projet React. Son gain est la réutilisation de Carte avec différentes props ; son coût est l’installation et la maintenance du projet.'],
  'http-methodes': ['HTTP', 'GET /api/livres HTTP/1.1\nHost: localhost:3000\nAccept: application/json', 'GET demande une lecture. Depuis le kit de l’atelier HTTP, lancez node server.js puis curl -i http://localhost:3000/api/livres pour voir la réponse réelle.', 'POST /api/livres HTTP/1.1\nHost: localhost:3000\nContent-Type: application/json\n\n{"titre":"Web"}', 'POST transporte ici un JSON de création. Le petit serveur de lecture du kit ne définit pas encore cette route : il faut l’ajouter et choisir 201 pour une création valide, 400 pour un titre invalide.'],
  'http-status': ['HTTP', 'HTTP/1.1 201 Created\nContent-Type: application/json\n\n{"id":1,"titre":"Web"}', '201 signifie que le serveur a créé une ressource ; le corps donne son identifiant public.', 'HTTP/1.1 400 Bad Request\nContent-Type: application/json\n\n{"erreur":"titre requis"}', '400 signifie que la demande manque une entrée requise. Le client ne doit pas la traiter comme un livre créé.'],
  'http-headers-cors': ['HTTP', 'GET /api/livres HTTP/1.1\nHost: localhost:3000\nOrigin: https://cours.example\nAccept: application/json', 'Origin identifie l’origine d’une page navigateur qui demande une ressource. Accept indique la représentation désirée.', 'HTTP/1.1 200 OK\nContent-Type: application/json\nAccess-Control-Allow-Origin: https://cours.example\n\n{"donnees":[]}', 'La réponse autorise cette origine à lire le JSON dans un navigateur. CORS ne remplace ni authentification ni autorisation sur chaque ressource.'],
  'shell-terminal': ['Bash / PowerShell', '# Bash / Zsh\npwd\nls\n# PowerShell\nGet-Location\nGet-ChildItem', 'Ces quatre lignes représentent deux paires alternatives. Exécutez seulement la paire adaptée : la première affiche votre dossier, la seconde son contenu. Ne copiez pas le symbole d’invite d’un tutoriel.'],
  'shell-pwd-ls-cd': ['Bash / Zsh', 'mkdir -p atelier-lecture\ncd atelier-lecture\npwd\ncd ..\npwd', 'Créez ce dossier uniquement dans un bac à sable. La première sortie se termine par atelier-lecture ; la seconde par son parent. cd .. désigne le parent, pas un dossier nommé .. .'],
  'shell-mkdir-touch': ['Bash / Zsh', 'mkdir -p essai/images\nprintf "Bonjour\\n" > essai/note.txt\nls -R essai', 'mkdir -p crée le sous-dossier ; printf écrit réellement un contenu, contrairement à touch qui crée seulement un fichier vide. ls vérifie la structure avant la suite.'],
  'shell-cp-mv-rm': ['Bash / Zsh', 'mkdir -p essai\nprintf "A\\n" > essai/note.txt\ncp essai/note.txt essai/copie.txt\nmv essai/copie.txt essai/archive.txt\nls -l essai', 'Le fichier initial reste et la copie change de nom. Vérifiez les deux fichiers avant toute suppression ; le bloc ne contient aucune commande destructive.'],
  'shell-cat-less-head-tail': ['Bash / Zsh', 'printf "un\\ndeux\\ntrois\\n" > essai.txt\nhead -n 2 essai.txt\ntail -n 1 essai.txt', 'head affiche un et deux ; tail affiche trois. Cette expérience crée son propre fichier pour éviter de supposer qu’un server.log existe.'],
  'shell-grep-rg-find': ['Bash / Zsh', 'mkdir -p essai\nprintf "TODO: vérifier\\n" > essai/note.txt\nfind essai -type f\ngrep -n "TODO" essai/note.txt', 'find affiche le chemin du fichier, grep affiche la ligne contenant TODO. rg peut remplacer grep si ripgrep est installé ; vérifiez sa disponibilité avant de l’utiliser.'],
  'shell-pipes-redirections': ['Bash / Zsh', 'printf "alpha\\nbeta\\n" > liste.txt\ncat liste.txt | grep "beta" > resultat.txt\ncat resultat.txt', 'Le pipe transmet la sortie de cat à grep, puis > remplace le contenu de resultat.txt par beta. Utilisez >> seulement si vous voulez ajouter sans écraser.'],
  'shell-env-path': ['Bash / PowerShell', '# Bash / Zsh\ncommand -v node\nprintf "%s\\n" "$PATH"\n# PowerShell\nGet-Command node\n$env:PATH', 'Ces lignes sont des alternatives selon le shell. La recherche de la commande et la variable PATH expliquent pourquoi un programme installé peut rester introuvable.'],
  'node-cli-check-watch': ['Terminal', 'printf "console.log(2 + 3);\\n" > exemple.js\nnode --check exemple.js\nnode exemple.js', 'Sur Bash/Zsh, ce bloc crée un vrai fichier avant de le vérifier puis l’exécuter ; la sortie est 5. Sous PowerShell, créez le fichier dans l’éditeur puis lancez les deux commandes node.'],
  'npm-ci-lockfile': ['Terminal', 'npm init -y\nnpm install express\n# package-lock.json vient d’être créé\nnpm ci\nnpm ls --depth=0', 'Faites l’essai dans un dossier vide. npm install crée le lockfile, npm ci réinstalle ses versions, npm ls rend visibles les versions présentes ; ne lancez pas npm ci avant d’avoir un lockfile.'],
  'npm-update-outdated-audit': ['Terminal', 'npm outdated\nnpm audit --omit=dev\nnpm update\nnpm test', 'outdated observe les versions disponibles, audit rapporte les vulnérabilités connues, update change des versions autorisées et test vérifie le comportement. Ne lancez pas audit fix à l’aveugle sur un projet important.'],
  'js-destructuration-avancee': ['JavaScript', 'const donnees = { id: 3, titre: "Web", prive: true };\nconst { prive, ...publicLivre } = donnees;\nconsole.log(publicLivre); // { id: 3, titre: "Web" }', 'La déstructuration extrait prive et le reste forme un nouvel objet superficiel. Si une propriété imbriquée est un objet, elle reste partagée : ce n’est pas une copie profonde.'],
  'js-regexp-pratique': ['JavaScript', 'const ligne = "Référence: AB-42";\nconst resultat = /^Référence: ([A-Z]{2})-(\\d+)$/.exec(ligne);\nconsole.log(resultat?.[1], resultat?.[2]); // AB 42', 'Les parenthèses capturent séparément le préfixe et le nombre textuel. Si la ligne ne correspond pas, exec renvoie null ; l’accès optionnel évite une panne mais il faut traiter l’absence.'],
  'css-proprietes-logiques': ['CSS', '.carte { padding-inline: 1rem; border-inline-start: 4px solid #0f766e; }\n[dir="rtl"] .carte { /* la bordure suit le début du texte */ }', 'inline-start suit la direction de l’écriture : la bordure se place au début logique au lieu de rester physiquement à gauche. Testez avec dir="ltr" puis dir="rtl" sur un conteneur HTML.'],
  'js-date-intl': ['JavaScript', 'const date = new Date("2026-10-01T14:30:00Z");\nconsole.log(new Intl.DateTimeFormat("fr-FR", { timeZone: "UTC", dateStyle: "short", timeStyle: "short" }).format(date));', 'timeZone: UTC fixe le fuseau pour un résultat comparable entre deux machines. Sans cette option, le fuseau local peut changer l’heure affichée, même si l’instant est identique.'],
  'javascript-abort-controller': ['JavaScript', 'const controleur = new AbortController();\nconst attente = fetch("/api/livres", { signal: controleur.signal });\ncontroleur.abort();\nattente.catch(erreur => { if (erreur.name !== "AbortError") console.error(erreur); });', 'L’abandon signale au fetch qu’il n’est plus utile. Un rejet AbortError est attendu ici ; les autres erreurs doivent rester visibles. L’annulation ne dispense pas de vérifier que la dernière recherche gagne.'],
  'next-cache-donnees': ['TypeScript', 'export default async function Page() {\n  const reponse = await fetch("https://example.com/catalogue.json", { cache: "no-store" });\n  if (!reponse.ok) throw new Error(`HTTP ${reponse.status}`);\n  const livres = await reponse.json();\n  return <pre>{JSON.stringify(livres, null, 2)}</pre>;\n}', 'Cet exemple de page serveur demande des données fraîches. L’URL doit pointer vers une vraie API JSON ; example.com est un emplacement fictif. Comparez avec la stratégie revalidate de la leçon après avoir défini une API de test.'],
  'frontend-bundler-build': ['Terminal', 'npm run build\n# Puis inspectez le dossier de sortie annoncé par votre outil :\nfind dist -maxdepth 2 -type f', 'Dans un projet Vite configuré, build produit les fichiers distribuables dans dist. Sur PowerShell, utilisez Get-ChildItem -Recurse dist. Vérifiez les chemins des ressources avant publication.'],
  'shell-installer-verifier-outil': ['Terminal selon système', '# Bash / Zsh\ncommand -v python3\npython3 --version\n# PowerShell\nGet-Command py\npy --version', 'La première commande localise l’outil, la seconde demande sa version. Exécutez seulement la paire de votre système ; une absence de commande se diagnostique avant de modifier PATH.'],
  'shell-powershell-bash': ['Terminal selon système', '# PowerShell\nGet-Location\nNew-Item -ItemType Directory -Name essai\nSet-Location essai\n# Bash / Zsh\npwd\nmkdir essai\ncd essai', 'Les trois intentions sont identiques : lire, créer, entrer. Les syntaxes ne sont pas interchangeables ; choisissez un bloc, ligne par ligne, dans un dossier d’exercice.'],
  'zero-fichiers': ['Gestionnaire de fichiers puis terminal facultatif', 'Documents/\n  bibliolearn-essai/\n    accueil.html\n    images/\n      portrait.png\n\n# Après la leçon terminal : ls bibliolearn-essai ou Get-ChildItem bibliolearn-essai', 'Commencez dans le gestionnaire de fichiers : ouvrez Documents, créez bibliolearn-essai puis images. Les commandes de la dernière ligne sont facultatives et dépendent du shell appris plus tard.'],
  'zero-web': ['HTTP à lire', 'GET /carnet HTTP/1.1\nHost: example.com\n\nHTTP/1.1 404 Not Found', 'Ce schéma montre une demande de page et une réponse absente. Il se lit, ne se colle pas dans un terminal. Le statut 404 indique que le serveur ne trouve pas cette ressource à ce chemin.'],
  'zero-outils': ['Terminal selon système', '# Si Python est nécessaire plus tard :\n# PowerShell Windows\npy --version\n# Bash / Zsh Linux ou macOS\npython3 --version', 'Exécutez seulement la ligne correspondant à votre système, après installation depuis une source officielle. Le résultat attendu est un numéro de version ; ce n’est pas encore l’exécution d’un programme Python.'],
  'js-callbacks': ['JavaScript', 'function effectuer(operation, valeur) { return operation(valeur); }\nconst resultat = effectuer(nombre => nombre * 2, 4);\nconsole.log(resultat); // 8', 'Le callback est la fonction passée comme argument. Ici l’appel est immédiat et synchrone ; callback ne signifie pas automatiquement asynchrone. La valeur renvoyée est réutilisable.'],
  'js-synchronisme': ['JavaScript', 'console.log("A");\nPromise.resolve().then(() => console.log("C"));\nconsole.log("B");\n// A, B, C', 'La fonction enregistrée avec then attend la fin du travail synchrone courant. Comparez ce résultat au setTimeout de la leçon ; la promesse et la minuterie n’utilisent pas la même file.']
};

function enrichir(fiches, ateliers) {
  return fiches.map(fiche => {
    if (fiche.sections.filter(s => s.type === 'code').length >= 2 || fiche.id === 'zero-ordinateur') return fiche;
    const propre = propres[fiche.id];
    const atelier = propre ? null : ateliers.find(a => a.associes.includes(fiche.id) && a.etapes.some(e => e.langage && !/Markdown|Protocole|Bash|Terminal/.test(e.langage) && e.code?.length > 25));
    const etape = atelier?.etapes.find(e => e.langage && !/Markdown|Protocole|Bash|Terminal/.test(e.langage) && e.code?.length > 25);
    if (!propre && !etape) return fiche;
    const [langage, contenu, explication, secondeVariation, secondeExplication] = propre || [etape.langage, etape.code, `${etape.explication} Ce fragment s’intègre aux fichiers de départ de l’atelier « ${atelier.titre} » ; sa validation est : ${atelier.validation[0]}. Ouvrez cet atelier pour copier tous les fichiers et les commandes de lancement.`];
    const sections = [...fiche.sections];
    const index = sections.findIndex(s => s.type === 'code');
    const insertion = Math.max(index, 0) + 1;
    const nouvellesSections = [
      { type: 'code', titre: propre ? 'Autre exemple à vérifier' : `Variation dans l’atelier : ${atelier.titre}`, langage, contenu, legende: propre ? 'Cet essai peut se faire dans un fichier ou une console propre ; suivez la préparation et lisez l’explication suivante.' : 'Fragment à intégrer au kit complet de l’atelier lié.' },
      { type: 'texte', titre: 'Ce que montre la variation', contenu: explication },
      ...(secondeVariation ? [{ type: 'code', titre: 'Comparer un deuxième cas', langage, contenu: secondeVariation }, { type: 'texte', titre: 'Lire la différence', contenu: secondeExplication }] : [])];
    sections.splice(insertion, 0, ...nouvellesSections);
    const sessions = fiche.sessions.map(session => ({ ...session,
      sections: session.sections.map(position => position >= insertion ? position + nouvellesSections.length : position) }));
    return { ...fiche, sections, sessions };
  });
}

module.exports = { enrichir };
